// ~500 chistes personalizados para la cuenta regresiva.
// Cada string es lo que va después de "Faltan X días para que".
// El componente arma: "Faltan {daysLeft} días para que {joke}"

export const JOKES: string[] = [
  // ═══════════════════════════════════════════════════════════════
  // SILVIA — SOGA AL CUELLO, AGUAFIESTAS, CONTROLA A DANIEL (~19)
  // ═══════════════════════════════════════════════════════════════
  "Silvia arme un Excel con los horarios de siesta de Daniel en el Palladium",
  "Silvia organice un itinerario de siestas más detallado que el del hotel",
  "Silvia sea nombrada Directora Honoraria de Siestas del Grand Palladium Select Bavaro",
  "Silvia le diga a Daniel 'vamos a la habitación que te leo un capítulo' a las 3 de la tarde en el Caribe",
  "Daniel mire la pileta por última vez antes de que Silvia lo lleve a 'descansar un ratito'",
  "Silvia saque a Daniel de la pileta después de 40 minutos diciendo 'ya estuvimos mucho rato' en un resort de 9 noches",
  "Pichi le diga a Silvia que el hotel la quiere contratar para dormir a los huéspedes que tienen insomnio",
  "Pichi le pregunte a Silvia qué organizó para la noche y Silvia diga 'un tecito en el balcón'",
  "Pichi invite a Silvia al karaoke y Silvia diga 'vayan ustedes, yo los espero leyendo'",
  "Silvia diga 'no exageren' cuando el barman todavía no terminó de cortar la primera lima",
  "Silvia apague la tele de la habitación a las 9 y Daniel escuche la fiesta de la pileta desde la cama",
  "Silvia le diga a Daniel 'vos no tomás más' y Daniel parpadee dos veces como señal de auxilio al barman",
  "Daniel pida un mojito y le llegue un tecito de manzanilla con una servilleta que dice 'Silvia'",
  "Silvia intercepte a Daniel camino a la barra como un control policial de la diversión",
  "Silvia le cuente los tragos a Daniel con los dedos desde el otro lado de la barra",
  "Silvia le diga al DJ que baje la música y el DJ le suba dos rayas",
  "Silvia le mande un WhatsApp a Daniel desde la habitación: 'ya es tarde, subí'... a las 8:30 PM",
  "Sebastian invite a Daniel a la barra y Silvia aparezca de la nada como si tuviera un GPS de la diversión",
  "Silvia prohíba bailar después de las 10 en un resort donde la fiesta arranca a las 11",
  "Silvia le diga a Daniel 'acompañame a la habitación' y Daniel diga 'pero qué voy a hacer ahí a las 3 de la tarde'",
  "Daniel se haga el dormido en la reposera para que Silvia no lo lleve a leer al balcón",
  "Silvia le confisque el segundo trago a Daniel como una maestra requisando un celular en clase",
  "Pichi le pregunte a Silvia a qué hora arranca la joda y Silvia conteste 'a las 8 apagamos todo'",
  "Silvia le ponga cara a Sebastian por pedir una segunda ronda a las 7 de la tarde",
  "Silvia diga 'vieron qué lindo el atardecer' mientras todos esperan que se vaya para pedir tragos",
  "Silvia se vaya a dormir y el volumen de la mesa suba tres niveles automáticamente",
  "Silvia lleve un rompecabezas de 1000 piezas a Punta Cana y lo arme en el balcón mientras suena la fiesta abajo",
  "Pichi le regale a Silvia un folleto de las actividades nocturnas del hotel envuelto como regalo de cumpleaños",
  "Silvia diga 'chicos, mañana hay que madrugar' sin que nadie haya reservado nada para mañana",
  "Daniel intente socializar con otros huéspedes y Silvia lo mire como diciendo 'ni se te ocurra'",
  "Silvia se siente en la barra VIP a tomar agua mineral y el barman la mire confundido",
  "Pichi presente a Silvia en la cena como 'la mujer que logró aburrir al Caribe'",
  "Silvia le diga a Daniel 'mañana nos levantamos temprano para aprovechar' y aprovechar sea leer en la reposera",
  "Silvia mire la fiesta de la pileta desde el balcón con los brazos cruzados como vigilando un recreo",
  "Silvia le diga a Sandra 'esto es mucho ruido' en un resort caribeño con animación 24 horas",
  "Daniel aprenda a pedir tragos con la mirada para que Silvia no lo vea hablar con el barman",
  "Silvia diga 'yo ya cené' a las 7 de la tarde y se vaya a la habitación con un yogur",
  "Pichi le diga a Silvia 'quedate un rato más' y Silvia agarre la cartera como si hubiera sonado una alarma de incendio",
  "Silvia le arme a Daniel la valija de vuelta el día 3 del viaje porque 'mejor ir preparando'",

  // ═══════════════════════════════════════════════════════════════
  // OMAR TORMENTAS + ARAJET (~35)
  // ═══════════════════════════════════════════════════════════════
  "Omar revise AccuWeather por décima vez buscando la tormenta tropical que arruine todo",
  "Omar mande un PDF al grupo de WhatsApp sobre la temporada de huracanes en el Caribe",
  "Omar calcule la probabilidad exacta de un huracán categoría 5 para el 27 de octubre",
  "Omar se queje de que Arajet no da ni un maní en el vuelo",
  "Omar googlee 'accidentes Arajet 2026' y comparta los resultados en el grupo familiar",
  "Omar descubra que en Arajet el asiento reclinable es un concepto filosófico",
  "Omar le explique a todos que las low cost no tienen los mismos estándares de seguridad",
  "Omar lleve un chaleco salvavidas propio al avión por si acaso",
  "Omar revise la ruta del huracán en tiempo real desde el celular en pleno vuelo de Arajet",
  "Omar se queje de que el espacio entre asientos de Arajet fue diseñado para hobbits",
  "Omar mande capturas del radar meteorológico al grupo a las 3 de la mañana",
  "Omar diga 'yo avisé' cuando caigan dos gotas de lluvia en Punta Cana",
  "Omar lleve un anemómetro personal a las vacaciones",
  "Omar pida cambiar de aerolínea faltando 3 días para el viaje",
  "Omar googlee '¿es seguro viajar a Punta Cana en octubre?' por centésima vez",
  "Omar se queje de que el equipaje de mano en Arajet es del tamaño de una cartera",
  "Omar compare los índices de seguridad de Arajet con los de Aerolíneas Argentinas sin ironía",
  "Omar le muestre a todos una app de rastreo de huracanes en la cena familiar",
  "Omar intente contratar un seguro específico contra huracanes categoría 3 o superior",
  "Omar le pregunte al piloto de Arajet si revisó bien el avión antes de despegar",
  "Omar saque estadísticas de por qué octubre es el peor mes para ir al Caribe",
  "Omar se queje del tamaño de la bandeja de Arajet como si fuera un crimen de lesa humanidad",
  "Omar descubra que 'low cost' también aplica al aire acondicionado del avión",
  "Omar proponga llevar comida de casa porque 'en Arajet no te dan nada'",
  "Omar le diga a Adriana que se despida del barrio por las dudas",
  "Omar investigue las rutas de evacuación del hotel en caso de huracán",
  "Omar pregunte en recepción del Palladium si el resort tiene búnker anti-huracanes",
  "Omar revise el pronóstico extendido a 45 días como si fuera un meteorólogo profesional",
  "Omar mande un audio de 5 minutos explicando por qué Arajet es peor que un colectivo",
  "Omar le pida a Sebastian que cambie los pasajes a American Airlines a último momento",
  "Omar descubra que la turbulencia en Arajet es una feature, no un bug",
  "Omar traiga un barómetro de viaje en la valija",
  "Omar se queje de que ni siquiera dan una galletita de agua en el vuelo",
  "Omar calcule que por el precio de Arajet les conviene ir nadando hasta Punta Cana",
  "Omar se agarre del apoyabrazos en cada turbulencia y le rece a tres santos distintos",

  // ═══════════════════════════════════════════════════════════════
  // SEBASTIAN SIDRA / BUFFET / FIESTA (~40)
  // ═══════════════════════════════════════════════════════════════
  "Sebastian descubra que la Sidra 1888 no está en el all-inclusive y tenga que conformarse con champagne",
  "Sebastian se llene 4 platos en el buffet y diga 'son vacaciones, no cuenta'",
  "Sebastian pregunte en la barra VIP si tienen Sidra 1888 importada desde Argentina",
  "Sebastian arme una torre de comida en el plato que desafíe las leyes de la gravedad",
  "Sebastian declare que el all-inclusive es su disciplina olímpica",
  "Sebastian vuelva al buffet por quinta vez diciendo 'solo voy a buscar el postre'",
  "Sebastian intente despachar una botella de Sidra 1888 como equipaje frágil",
  "Sebastian haga un brindis con lo que sea que tenga en la mano, aunque sea agua",
  "Sebastian calcule cuántos platos de buffet necesita comer para amortizar el viaje entero",
  "Sebastian descubra que puede repetir infinitas veces en el buffet y llore de emoción",
  "Sebastian llene el plato como si fuera la última cena de su vida",
  "Sebastian diga 'este buffet me necesita a mí' en vez de 'yo necesito este buffet'",
  "Sebastian investigue si el all-inclusive cubre el cuarto almuerzo del día",
  "Sebastian haga competencia de platos llenos con Bruno y Nani en el buffet",
  "Sebastian intente explicarle a un bartender dominicano qué es la Sidra 1888",
  "Sebastian diga 'estoy probando de todo' mientras repite el mismo plato por sexta vez",
  "Sebastian cierre la barra VIP a las 4 AM y abra el buffet del desayuno sin pasar por la cama",
  "Sebastian proponga 'un brindis' cada 20 minutos hasta que se quede sin excusas",
  "Sebastian descubra el buffet de medianoche y no vuelva a ser la misma persona",
  "Sebastian lleve pantalones con elástico 'por las dudas' al viaje",
  "Sebastian convierta el minibar de la habitación en su bodega personal de Sidra 1888",
  "Sebastian haga un ranking exhaustivo de los 7 restaurantes del resort",
  "Sebastian pida un waiver oficial para el límite de platos por persona en el buffet",
  "Sebastian necesite pantalones nuevos después del tercer día de buffet libre",
  "Sebastian descubra que hay 7 restaurantes y quiera cenar en todos en una sola noche",
  "Sebastian use más el buffet que la playa, la pileta y el spa combinados",
  "Sebastian se pare en la fila del buffet 10 minutos antes de que abra",
  "Sebastian invente un coctel que combine champagne con algo que se parezca a la 1888",
  "Sebastian se haga amigo del chef del buffet para pedirle porciones extra",
  "Sebastian descubra el room service a las 3 AM y considere no salir más de la suite",
  "Sebastian proponga 'una última copa' por decimoséptima vez en la noche",
  "Sebastian apile sushi, pasta y carne en el mismo plato y lo llame 'fusión argentina'",
  "Sebastian calcule cuántas calorías por dólar consume en el all-inclusive",
  "Sebastian le gane un mano a mano al buffet del Palladium",
  "Sebastian tenga un sexto sentido para detectar cuándo reponen un plato nuevo",
  "Sebastian haga un álbum de fotos dedicado exclusivamente a sus platos del buffet",
  "Sebastian confunda el restaurante japonés con el buffet libre y pida 'de todo un poco'",
  "Sebastian necesite dos reposeras: una para él y otra para la digestión post-buffet",
  "Sebastian vuelva de Punta Cana rodando por el pasillo de Arajet",
  "Sebastian intente convencer al barman de que la Sidra 1888 es una bebida premium internacional",

  // ═══════════════════════════════════════════════════════════════
  // VANESA JODONA (~35)
  // ═══════════════════════════════════════════════════════════════
  "Vanesa le esconda la toalla a Stella en la playa y se haga la desentendida",
  "Vanesa le cambie el protector solar a Bruno por bronceador sin avisar",
  "Vanesa ponga una alarma a las 6 AM en el celular de otra persona dormida",
  "Vanesa le mueva la reposera a Daniel mientras duerme la siesta y lo deje al sol",
  "Vanesa le diga a Silvia que Daniel está en la barra en vez de durmiendo",
  "Vanesa le ponga arena en las ojotas a Bruno cuando no esté mirando",
  "Vanesa convenza a Valentino y Juli de que hay tiburones en la pileta",
  "Vanesa le pida al DJ que ponga reggaetón a todo volumen cuando todos quieren dormir",
  "Vanesa esconda las llaves de la habitación de Omar y se haga la inocente",
  "Vanesa le saque fotos dormidos a todos para subirlas al grupo de WhatsApp",
  "Vanesa le diga a Omar que vio una nube sospechosa en el horizonte y lo mire disfrutar",
  "Vanesa le cambie el idioma del celular a Daniel al mandarín",
  "Vanesa le cuente a Stella que el agua del resort puede tener bacterias exóticas",
  "Vanesa invente que hay una actividad obligatoria a las 7 AM y despierte a todos",
  "Vanesa le diga a Sebastian que el buffet cerró temprano solo para verle la cara",
  "Vanesa le tire agua a Daniel dormido en la reposera y salga corriendo",
  "Vanesa le ponga un cangrejo de plástico en la cama de Stella y espere los gritos",
  "Vanesa le diga a Alejandro que el minibar no es gratis para ver su expresión de terror",
  "Vanesa organice un karaoke obligatorio sin el consentimiento de nadie",
  "Vanesa grabe los mejores videos vergonzosos del viaje para el grupo familiar",
  "Vanesa le diga a Pichi que un huésped se ofendió con su último chiste",
  "Vanesa le cambie la reserva del restaurante a otra fecha sin avisar",
  "Vanesa convenza a todos de ir a una excursión a las 6 AM después de una noche de fiesta",
  "Vanesa le diga a Silvia que vio a Daniel tomando tragos a escondidas durante la siesta",
  "Vanesa le esconda el botiquín a Stella y disfrute el caos hipocondríaco",
  "Vanesa invente un rumor sobre una fiesta temática de disfraces obligatoria",
  "Vanesa le ponga el despertador a las 5 AM a Sebastian después de cerrar la barra",
  "Vanesa proponga un juego de verdad o reto en la pileta que nadie pidió",
  "Vanesa le cuente a Omar que leyó sobre un terremoto reciente en República Dominicana",
  "Vanesa le mueva las cosas de la habitación de Sandra mientras están en la playa",
  "Vanesa publique las peores fotos de todos en sus stories de Instagram",
  "Vanesa le diga a Roque que el agua de la pileta está helada para verlo dudar",
  "Vanesa organice una broma grupal contra Sebastian coordinando a los nenes",
  "Vanesa le cambie el ringtone del celular a Daniel por un canto de gallo",
  "Vanesa convenza a Valentino y Juli de despertar a todos tirándoles almohadas",

  // ═══════════════════════════════════════════════════════════════
  // BRUNO / NANI / SEBA CREW FIESTA (~40)
  // ═══════════════════════════════════════════════════════════════
  "Bruno, Nani y Sebastian cierren la barra VIP a las 4 AM por tercera noche consecutiva",
  "Bruno, Nani y Sebastian descubran que el all-inclusive tiene barra 24 horas y se les iluminen los ojos",
  "Bruno, Nani y Sebastian hagan un pacto sagrado de no dormirse antes de las 5 AM",
  "Sebastian le proponga a Bruno y Nani 'una última copa' por vigésima vez en la noche",
  "Bruno intente hacer bomba en la pileta a las 2 AM mientras Nani filma",
  "Nani desafíe a Bruno a ver quién toma más mojitos en una hora",
  "Sebastian, Bruno y Nani se pierdan el desayuno por tercera vez consecutiva",
  "Bruno haga un brindis individual por cada uno de los 19 miembros de la familia",
  "Nani se haga tan amigo del barman que le sirvan tragos off-menu",
  "Sebastian, Bruno y Nani aparezcan al desayuno con lentes de sol y sin capacidad de habla",
  "Bruno descubra que la disco del hotel existe y desaparezca por horas",
  "Nani proponga ir a un club nocturno en Bávaro y volver justo para el desayuno",
  "Sebastian, Bruno y Nani tengan su propia mesa VIP reservada en la barra todas las noches",
  "Bruno convierta cualquier rincón del resort en una pista de baile improvisada",
  "Nani descubra las fiestas de espuma del hotel y las declare su lugar feliz",
  "Sebastian le enseñe a los bartenders dominicanos a hacer fernet con coca",
  "Bruno, Nani y Sebastian aprendan a bailar bachata después del tercer trago",
  "Nani se quede dormido en la reposera de la playa y se despierte al amanecer",
  "Bruno intente convencer a Pamela de que anoche volvió temprano a la habitación",
  "Sebastian cierre la disco y abra el desayuno sin pasar por la habitación en ningún momento",
  "Bruno y Nani descubran que en el VIP los tragos vienen dobles automáticamente",
  "Sebastian proponga 'solo una copa antes de dormir' a las 2 AM con total seriedad",
  "Bruno, Nani y Sebastian inventen un coctel nuevo y le pongan un nombre argentino épico",
  "Nani se quede bailando solo en la pista cuando Bruno y Sebastian ya se fueron a dormir",
  "Bruno haga karaoke a las 3 AM y despierte a medio piso del hotel",
  "Sebastian, Bruno y Nani compitan por quién conoce más gente nueva en una noche",
  "Bruno diga 'esta es la mejor noche de mi vida' absolutamente todas las noches",
  "Nani proponga ir a la playa de noche 'solo para ver las estrellas' con un trago en la mano",
  "Sebastian, Bruno y Nani lleguen a la habitación justo cuando otros salen a desayunar",
  "Bruno intente tirarse a la pileta de noche y Pamela lo agarre del brazo a último segundo",
  "Nani se quede dormido en un sillón del lobby esperando a que los demás se preparen",
  "Sebastian invite a un grupo de desconocidos a tomar shots con la familia argentina",
  "Bruno descubra el minibar de la suite VIP y considere seriamente no salir de la habitación",
  "Sebastian, Bruno y Nani se pierdan la excursión del día siguiente por culpa de la resaca",
  "Nani haga más amigos en la barra en una noche que Pichi en todo el viaje",
  "Bruno proponga 'repetir la noche anterior pero más tranqui' y termine exactamente igual",
  "Sebastian tome champagne como si fuera Sidra 1888 y nadie note la diferencia",
  "Bruno, Nani y Sebastian vuelvan con más fotos en la barra que en la playa",
  "Nani descubra que el DJ del hotel acepta pedidos y no lo deje en paz toda la noche",
  "Sebastian, Bruno y Nani calculen que durmieron un total de 15 horas entre los tres en 9 noches",

  // ═══════════════════════════════════════════════════════════════
  // VALENTINO Y JULI - NENES (~30)
  // ═══════════════════════════════════════════════════════════════
  "Valentino y Juli conviertan la pileta de adultos en un parque acuático no autorizado",
  "Valentino tire una bomba en la pileta que moje a medio hotel incluyendo las reposeras",
  "Juli le grite '¡mirá papi!' a Nani 47 veces por hora sin excepción",
  "Valentino y Juli descubran que el helado del resort es ilimitado y pierdan la cabeza",
  "Valentino persiga cangrejos en la playa hasta que Stella entre en pánico real",
  "Juli quiera bañarse en la pileta a las 7 AM cuando nadie se levantó todavía",
  "Valentino y Juli gasten más energía en una mañana que el generador del hotel en un día",
  "Juli pregunte '¿cuándo llegamos?' cada 5 minutos durante todo el vuelo de Arajet",
  "Valentino descubra los toboganes acuáticos del resort y se niegue a hacer cualquier otra cosa",
  "Juli y Valentino se llenen de arena hasta en lugares anatómicamente imposibles",
  "Valentino pida helado de desayuno, de almuerzo, de merienda y de cena sin negociar",
  "Juli haga un castillo de arena más ambicioso que la suite junior",
  "Valentino y Juli corran por el lobby del hotel como si fuera una cancha de fútbol 5",
  "Juli quiera llevar un cangrejo vivo de mascota en el avión de vuelta",
  "Valentino tire la bomba del siglo en la pileta justo cuando Roque se estaba relajando",
  "Juli y Valentino pregunten '¿hay wifi?' parados en la orilla del mar Caribe",
  "Valentino descubra que puede repetir postre infinitas veces y entre en éxtasis",
  "Juli convenza a Valentino de competir quién aguanta más bajo el agua hasta asustar a todos",
  "Valentino y Juli transformen el buffet de postres en una zona de guerra de servilletas",
  "Juli le pida al barman un coctel 'como el de papá' con total naturalidad",
  "Valentino y Juli descubran los shows nocturnos del hotel y se nieguen a ir a dormir",
  "Valentino le salpique agua a Omar justo cuando está leyendo el pronóstico del tiempo",
  "Juli le pregunte a Stella si las cremas del botiquín son para jugar a los doctores",
  "Valentino y Juli se pierdan en el resort y aparezcan en el spa de adultos",
  "Juli quiera dormir en la reposera de la playa en vez de volver a la habitación",
  "Valentino convierta las duchas de la pileta en un parque de diversiones personal",
  "Juli y Valentino agoten a Pamela y Vanesa antes del mediodía del primer día",
  "Valentino haga amigos con todos los nenes del hotel en los primeros 10 minutos",
  "Juli llore porque el avión de Arajet no tiene pantallita individual",
  "Valentino y Juli tengan más energía a las 10 PM que todos los adultos a las 10 AM",

  // ═══════════════════════════════════════════════════════════════
  // FRANCESCA Y SOFI - TEENS (~25)
  // ═══════════════════════════════════════════════════════════════
  "Francesca y Sofi hagan 400 selfies con el atardecer caribeño y ninguna les guste",
  "Francesca y Sofi evalúen cada rincón del resort por su potencial instagrameable",
  "Sofi pida la contraseña del wifi antes de preguntar dónde queda la playa",
  "Francesca y Sofi le saquen una foto a cada coctel del bar sin probar ninguno",
  "Francesca descubra que el resort tiene sesiones de fotos profesionales incluidas",
  "Sofi diga 'esto lo vi en TikTok' cada vez que Silvia proponga cualquier actividad",
  "Francesca y Sofi se hagan amigas de otros adolescentes del resort en 5 minutos exactos",
  "Sofi evalúe los 9 días de viaje basándose exclusivamente en la calidad del wifi",
  "Francesca haga un reel de cada plato del buffet antes de dar el primer bocado",
  "Francesca y Sofi se queden despiertas hasta las 3 AM scrolleando TikTok en la cama",
  "Sofi le enseñe a Roque a usar filtros de Instagram con paciencia infinita",
  "Francesca y Sofi desaparezcan en el club de teens del resort y no las veamos en días",
  "Sofi encuentre el ángulo perfecto para la foto de la pileta después de 47 intentos",
  "Francesca le diga a Pamela que por favor no la etiquete en fotos vergonzosas familiares",
  "Francesca y Sofi hagan más fotos que recuerdos reales durante todo el viaje",
  "Sofi proponga cambiar de restaurante porque la iluminación no es buena para fotos",
  "Francesca descubra que hay actividades organizadas para teens y no vuelvan a ver a sus padres",
  "Sofi diga 'esto queda en mi highlight de Punta Cana' aproximadamente 300 veces",
  "Francesca y Sofi se mueran de vergüenza cuando Pichi hable con sus nuevos amigos del resort",
  "Sofi le explique a Omar cómo funciona el filtro del clima en su celular",
  "Francesca y Sofi consuman más datos móviles que todo el grupo familiar junto",
  "Sofi se queje de que la playa no tiene el color exacto que sale en el folleto",
  "Francesca haga un vlog completo del viaje que probablemente nadie más que ella mire",
  "Francesca y Sofi se resistan a las actividades familiares porque son 'cringe total'",
  "Sofi le pida a Sebastian que le saque una foto 'natural' y le dirija 47 tomas diferentes",

  // ═══════════════════════════════════════════════════════════════
  // ALEJANDRO Y OMAR — DÚOS OPUESTOS (~15)
  // Omar se queja de todo, Alejandro disfruta que todo es gratis
  // ═══════════════════════════════════════════════════════════════
  "Omar se queje de la excursión en catamarán y Alejandro diga 'pero es gratis, Omar' con la sonrisa más grande del Caribe",
  "Omar analice los riesgos del viaje y Alejandro esté al lado pidiendo su tercer trago gratis sin escucharlo",
  "Alejandro le diga a Omar 'relajate, es all-inclusive' cada vez que Omar abra la boca para quejarse",
  "Omar proponga una queja formal y Alejandro le diga 'dejá de quejarte y pedite otro trago que no te cobran'",
  "Omar calcule los riesgos de la excursión y Alejandro ya esté arriba del catamarán con un coctel en la mano",
  "Alejandro descubra que hasta el spa es gratis y mire a Omar como diciendo 'ves que valía la pena'",
  "Omar le lea a Alejandro un artículo sobre riesgos tropicales y Alejandro le pase un trago sin decir nada",
  "Alejandro disfrute cada segundo del all-inclusive mientras Omar encuentra un defecto nuevo cada hora",
  "Omar diga 'esto en Argentina no pasa' y Alejandro le conteste 'en Argentina tampoco es gratis'",
  "Omar y Alejandro terminen el viaje siendo los que más la pasaron bien, cada uno a su manera",

  // ═══════════════════════════════════════════════════════════════
  // STELLA HIPOCONDRÍACA (~25)
  // ═══════════════════════════════════════════════════════════════
  "Stella meta en la valija un botiquín más grande que toda su ropa junta",
  "Stella le embadurne repelente a todos cada 47 minutos sin preguntar",
  "Stella googlee 'enfermedades tropicales República Dominicana 2026' y le dé un micro-infarto",
  "Stella desinfecte la habitación del hotel de punta a punta antes de deshacer la valija",
  "Stella lleve termómetro, oxímetro, tensiómetro y botiquín de campaña militar",
  "Stella le pregunte al médico del hotel si hubo casos de dengue este mes",
  "Stella revise la fecha de vencimiento de cada cosa que sirvan en el buffet",
  "Stella lleve alcohol en gel para cada bolsillo de cada prenda de cada miembro de la familia",
  "Stella se ponga repelente encima del protector encima del repelente otra vez",
  "Stella pregunte si el agua de la pileta está tratada con la concentración correcta de cloro",
  "Stella investigue cuál es el hospital más cercano al resort y cómo llegar a pie",
  "Stella le diga a todos que no caminen descalzos por la arena porque hay parásitos",
  "Stella desinfecte los cubiertos del restaurante con toallitas aunque estén recién lavados",
  "Stella lleve pastillas para el mareo, el dolor, la alergia, el estómago, el sol y el aburrimiento",
  "Stella le ponga protector solar a Pichi incluso en un día completamente nublado",
  "Stella se autodiagnostique dengue por una picadura de mosquito normal",
  "Stella pregunte si las sábanas del hotel son hipoalergénicas y orgánicas",
  "Stella lleve mascarillas N95 para el vuelo de Arajet 'por el aire recirculado'",
  "Stella sea la única persona que lea el folleto de seguridad del hotel completo dos veces",
  "Stella confunda un bronceado normal con una reacción alérgica grave",
  "Stella tenga el número del médico del hotel guardado como contacto favorito",
  "Stella revise si cada botella de agua del minibar está perfectamente sellada",
  "Stella le diga a Valentino que no toque absolutamente nada sin lavarse las manos primero",
  "Stella lleve un kit de primeros auxilios que pese más que su equipaje de mano",
  "Stella sugiera no ir a la playa un día porque leyó un artículo sobre medusas en el Caribe",

  // ═══════════════════════════════════════════════════════════════
  // PICHI SINVERGÜENZA (~25)
  // ═══════════════════════════════════════════════════════════════
  "Pichi le cuente un chiste malo a un turista alemán que no habla ni una palabra de español",
  "Pichi se haga amigo personal del gerente del Palladium en las primeras 2 horas del check-in",
  "Pichi le haga un chiste al piloto de Arajet mientras embarca y la azafata no sepa qué hacer",
  "Pichi invite a una familia brasileña completa a tomar algo en nuestra mesa",
  "Pichi le cuente su vida entera al taxista del aeropuerto de Punta Cana en el trayecto",
  "Pichi conozca a más huéspedes del resort que el mismísimo personal de recepción",
  "Pichi haga reír a un mozo del restaurante tanto que se le caiga la bandeja",
  "Pichi le pregunte al DJ si puede subir al escenario a cantar una canción con él",
  "Pichi se meta en una conversación ajena en la pileta y termine siendo el protagonista absoluto",
  "Pichi les describa un asado argentino a unos turistas canadienses con detalles épicos",
  "Pichi le diga 'amigo' a un guardia de seguridad que acaba de conocer hace 30 segundos",
  "Pichi le cuente chistes al personal de limpieza todas las mañanas como si fuera stand-up",
  "Pichi organice una peña folclórica improvisada en el lobby del Palladium",
  "Pichi se haga amigo de toda la mesa de al lado en el restaurante antes del primer plato",
  "Pichi le pregunte a un turista francés si sabe lo que es un verdadero asado con cuero",
  "Pichi anime un karaoke en el bar sin que absolutamente nadie se lo haya pedido",
  "Pichi haga avergonzar a Francesca y Sofi delante de sus nuevos amigos adolescentes del resort",
  "Pichi le cuente la historia completa del viaje familiar a cada persona que se cruce",
  "Pichi le haga tantos chistes al barman que le empiecen a servir tragos dobles de simpatía",
  "Pichi transforme una excursión grupal tranquila en su show de stand-up personal",
  "Pichi le diga a un huésped desprevenido que él es parte del staff de entretenimiento del hotel",
  "Pichi haga más contactos en 9 días de vacaciones que un networker en LinkedIn en un año",
  "Pichi tenga más fotos con desconocidos del resort que con su propia familia",
  "Pichi le haga un chiste a un turista alemán en la fila del buffet y termine cenando con él",
  "Pichi haga que Stella se tape la cara de vergüenza al menos 3 veces por día",

  // ═══════════════════════════════════════════════════════════════
  // PAMELA VS BRUNO (~15)
  // ═══════════════════════════════════════════════════════════════
  "Pamela le diga a Bruno '¿dónde están los nenes?' y Bruno esté tirándose de bomba en la pileta",
  "Bruno salga del baño y se tire de bomba en la pileta mientras Pamela lo busca para que cuide a Valentino y Francesca",
  "Pamela diga '¿DÓNDE ESTÁ BRUNO?' y Bruno esté en su mundo haciendo la plancha en la pileta",
  "Bruno desaparezca con Sebastian y Nani mientras Pamela se queda con los chicos por enésima vez",
  "Pamela le pida a Bruno que vigile a Valentino 5 minutos y a los 2 minutos Bruno esté en la barra",
  "Bruno diga 'ya vuelvo, voy al baño' y aparezca 40 minutos después mojado de la pileta",
  "Pamela recorra medio resort buscando a Bruno y lo encuentre haciendo competencias de bomba con Valentino",
  "Bruno se haga el que no escucha cuando Pamela lo llama porque está en la mitad de una carrera de nado con Nani",
  "Pamela le deje a los nenes a Bruno 10 minutos y Bruno los lleve a los tres al sport bar",
  "Bruno sale corriendo del baño, se tira de bomba en la pileta, y Pamela lo ve justo cuando se da vuelta",
  "Pamela calcule que Bruno pasó más horas en la barra que con sus propios hijos en todo el viaje",
  "Bruno diga 'estoy con los chicos' mientras los chicos están con Pamela y Bruno está pidiendo un mojito",
  "Pamela le mande 4 mensajes seguidos a Bruno y Bruno tenga el celular en la reposera a 200 metros",
  "Bruno se ofrezca a llevar a los nenes a la pileta y termine él jugando mientras los nenes miran",
  "Pamela le diga a Francesca 'buscá a tu padre' y Francesca lo encuentre haciendo karaoke en el bar",

  // ═══════════════════════════════════════════════════════════════
  // MARCELA - NO VIENE (~15)
  // ═══════════════════════════════════════════════════════════════
  "Marcela no pueda intentar pasar 10 kg de yerba Amanda por la aduana dominicana esta vez",
  "Marcela no esté para exigirle flores frescas al mozo en cada mesa del restaurante",
  "Marcela nos mande un audio de 7 minutos quejándose de que nadie la invitó",
  "Marcela no pueda obligar a las meseras del Palladium a poner centros de mesa florales",
  "Marcela descubra nuestras fotos del viaje en Instagram y se arrepienta de no haber venido",
  "Marcela nos mande la lista completa de todo lo que nos estamos perdiendo por no llevar yerba",
  "extrañemos los mates de Marcela con yerba Amanda en la playa... o quizás no tanto",
  "Marcela no esté para reorganizar la disposición de cada mesa del restaurante a su gusto",
  "Marcela no pueda redecorar la habitación del hotel con arreglos florales improvisados",
  "el grupo entero se acuerde de cuando casi la paran en el aeropuerto por los paquetes de yerba Amanda",
  "Marcela mande fotos de su mate solitario con Amanda desde Argentina mientras nosotros estamos en la playa",
  "ningún mozo del Palladium sea obligado a poner flores en la mesa y pueda trabajar en paz",
  "Marcela pregunte por WhatsApp si estamos tomando mate allá con tono de decepción",
  "nos demos cuenta de que sin Marcela nadie exige decoración floral en la cena",
  "Marcela nos mande un tutorial por WhatsApp de cómo hacer mate con agua del Caribe",

  // ═══════════════════════════════════════════════════════════════
  // SAN CLEMENTE → PUNTA CANA (~20)
  // ═══════════════════════════════════════════════════════════════
  "revivamos los veranos en San Clemente del Tuyú, pero esta vez con pulsera VIP del Palladium",
  "Pichi le explique a un turista que en San Clemente la heladería top se llamaba Pirulo y lo diga con orgullo",
  "pasemos de comprar fiambre en La Baticueva de San Clemente a buffet libre en el Palladium",
  "cambiemos los colchones en el piso de la casa de San Clemente por camas king size con vista al Caribe",
  "Vanesa diga 'yo extraño La Baticueva' en el medio del buffet del Palladium y todos se tienten",
  "Valentino pregunte '¿qué es un Pirulo?' y Silvia le diga 'algo que no necesitás saber, hijo'",
  "pasemos de dormir 15 personas en una casa con 3 habitaciones en San Clemente a suites individuales en Punta Cana",
  "cambiemos el Fernet playero de San Clemente por cocktails VIP en el Caribe",
  "los adultos organicen un policía y ladrón en los jardines del Palladium como en el Vivero de San Clemente",
  "pasemos de los helados horribles de la heladería Pirulo en San Clemente a los helados artesanales del resort",
  "recordemos cuando la 'excursión familiar' era caminar hasta el faro de San Clemente",
  "Sebastian proponga jugar al policía y ladrón en el resort y los adultos terminen corriendo entre palmeras como en el Vivero",
  "nos saquemos la foto grupal en el Caribe como la sacábamos en la playa de San Clemente",
  "extrañemos La Baticueva cuando veamos que el minibar del Palladium no tiene fiambre cortado",
  "los chicos se escondan en el resort y los adultos los busquen como en el policía y ladrón del Vivero de San Clemente",
  "Sebastian le diga al barman del Palladium 'esto en La Baticueva salía dos mangos' y el barman no entienda nada",
  "pasemos de San Clemente del Tuyú a Bávaro, Punta Cana, y nadie pueda creerlo",
  "nos demos cuenta de que la familia creció de colchones en el piso en San Clemente a 5 estrellas en el Caribe",
  "Pichi cuente en el Palladium que antes dormíamos todos en el piso y los turistas no le crean",
  "Pichi diga 'el helado de Pirulo era mejor' con total ironía mirando el helado artesanal del resort",
  "Sebastian se esconda en el jardín del resort y grite 'policía y ladrón como en el Vivero' y todos los adultos salgan corriendo",
  "recordemos las noches en San Clemente peleándonos por quién dormía en el colchón más cerca del ventilador",
  "cambiemos las compras de último momento en La Baticueva por el room service las 24 horas del Palladium",
  "Silvia diga 'La Baticueva tenía mejores precios' comparando con la tiendita del resort",

  // ═══════════════════════════════════════════════════════════════
  // ALL-INCLUSIVE / VIP / BUFFET (~40)
  // ═══════════════════════════════════════════════════════════════
  "Alejandro pregunte '¿el minibar también es all-inclusive?' por quinta vez en el viaje",
  "19 argentinos invadan el buffet del Palladium como si no existiera el mañana",
  "Sebastian descubra que los tragos VIP son dobles y entre en un estado de gracia permanente",
  "la familia entera aplique la estrategia oficial de 'comer como si no hubiera vuelta'",
  "la pulsera VIP se convierta en la joya más preciada y querida de todo el viaje",
  "Sebastian arme un plato tan alto en el buffet que necesite escolta hasta la mesa",
  "el personal del buffet reconozca a nuestra familia por la cantidad récord de repeticiones",
  "todos descubramos que 'all-inclusive' es el concepto más hermoso del idioma español",
  "Bruno intente meter sushi, pasta, carne y postre en un solo plato y lo logre",
  "la barra VIP del Palladium se quede sin hielo por primera vez en su historia",
  "Sebastian pregunte '¿puedo llevar comida a la habitación?' con voz bajita y cara de culpa",
  "el barman VIP vea venir a nuestra familia y empiece a preparar tragos antes de que pidamos",
  "Bruno descubra el snack bar de las 3 AM y le cambie la vida para siempre",
  "la familia consuma más helado en 9 días que un crucero entero en un mes",
  "Nani se ponga el pijama para ir al buffet de medianoche sin ninguna vergüenza",
  "el chef del Palladium aprenda qué es el dulce de leche argentino gracias a nosotros",
  "la familia pida 'un poquito más por favor' en cada restaurante del resort",
  "descubramos que el VIP del Socio Travel Club valió cada centavo invertido",
  "Pichi confunda el lobby bar con su living personal y se instale ahí permanentemente",
  "la familia deje reviews mentales de cada restaurante como si fueran críticos gastronómicos profesionales",
  "la barra VIP necesite un delivery urgente de ron por culpa de nuestra familia",
  "Omar descubra que los cocktails tropicales tienen nombres imposibles de pronunciar y los critique",
  "nos deprima genuinamente volver a tener que cocinar después de 9 días de buffet ilimitado",
  "la pulsera all-inclusive genere más felicidad colectiva que cualquier regalo de Navidad",
  "Sebastian intente llevarse una bandeja entera del buffet como souvenir del viaje",
  "el staff del Palladium cuente la leyenda de la familia argentina de 19 personas durante años",
  "Sebastian repita el mismo plato 4 veces en la misma cena y diga 'estoy probando variaciones'",
  "la familia argentina demuestre que 19 personas pueden efectivamente vaciar un buffet",
  "descubramos que la membresía VIP incluye beneficios que ni sabíamos que existían",
  "Daniel tenga que aflojarse el cinturón después del segundo almuerzo del día",
  "la familia necesite una reposera extra solo para la digestión colectiva post-buffet",
  "el buffet del Palladium tenga flashbacks de nuestra visita durante los próximos 5 años",
  "Sebastian haga un brindis con un coctel tropical diferente cada noche de los 9 días",
  "la familia pruebe absolutamente todos los restaurantes del hotel en los primeros 3 días",
  "Bruno descubra que hay pizza a las 4 AM, lo grite al pasillo y despierte a medio piso",
  "la familia convierta cada comida del día en una reunión familiar extendida de 2 horas",
  "el Palladium contrate personal de refuerzo para el buffet cuando vea nuestra reserva de 19",
  "Sebastian pregunte si existe un límite de visitas al buffet por día y le digan que no",
  "descubramos que la mejor propina en el all-inclusive es la sonrisa genuina al barman",
  "la familia le dé una masterclass práctica a otros huéspedes sobre cómo exprimir el all-inclusive",

  // ═══════════════════════════════════════════════════════════════
  // PATRIARCADO / HOMBRES (~15)
  // ═══════════════════════════════════════════════════════════════
  "los hombres finjan que ayudan a empacar las valijas mientras miran el partido en el celular",
  "los hombres digan 'yo llevo las valijas' como si fuera una proeza del patriarcado argentino",
  "los hombres se ofrezcan a 'cuidar las reposeras' mientras las mujeres llevan a los nenes a la pileta",
  "los hombres descubran que en el all-inclusive también hay que servirse solos el plato",
  "los hombres debatan 40 minutos a qué restaurante ir y terminen todos en el buffet de siempre",
  "los hombres digan 'yo me encargo de la logística' y terminen pidiendo indicaciones a las mujeres",
  "Bruno, Nani y Sebastian digan 'nosotros armamos el plan' y Pamela, Vanesa y Silvia lo rehagan entero",
  "los hombres se adjudiquen haber elegido el resort después de que las mujeres lo investigaron durante semanas",
  "los hombres se quejen de la crema solar y las mujeres los embadurnen a la fuerza como a nenes",
  "Daniel, Omar y Alejandro se sienten en la reposera a 'pensar' mientras los demás organizan todo",
  "los hombres lleven una valija cada uno y las mujeres lleven la logística completa de 19 personas",
  "los hombres propongan 'actividad de hombres' que consiste únicamente en ir a la barra",
  "los hombres digan que ellos coordinaron el viaje sin saber ni la dirección del resort",
  "Sebastian diga 'yo organicé todo el viaje' cuando su mamá le armó la valija",
  "los hombres se atribuyan el éxito del viaje en la cena de despedida y las mujeres se miren entre ellas",

  // ═══════════════════════════════════════════════════════════════
  // VUELOS / AEROPUERTO (~15)
  // ═══════════════════════════════════════════════════════════════
  "Silvia cree un grupo de WhatsApp con las reglas oficiales del viaje y mande 47 audios",
  "Omar revise el pronóstico del tiempo en Ezeiza antes de embarcar y diga 'hay nubes sospechosas'",
  "Omar se queje del proceso de check-in de Arajet como si fuera una odisea griega",
  "Stella lleve más equipaje de mano que equipaje facturado y la paren en el gate",
  "los nenes pregunten '¿ya llegamos?' antes de que el avión de Arajet despegue",
  "Stella desinfecte el asiento de Arajet con toallitas antibacteriales como en una operación quirúrgica",
  "Omar descubra en el aeropuerto que Arajet tiene asignación libre de asientos y le agarre un ataque",
  "19 personas intenten coordinarse para sentarse cerca en el avión de Arajet sin éxito",
  "Omar se agarre del apoyabrazos en cada mínima turbulencia y le rece a tres santos distintos",
  "Sebastian se lleve medio buffet del aeropuerto de Ezeiza 'para el viaje de 5 horas'",
  "la familia ocupe una fila completa del gate de embarque en Ezeiza",
  "Sebastian intente despachar una botella de Sidra 1888 como equipaje frágil con total seriedad",
  "19 argentinos hagamos la fila más ruidosa y divertida del aeropuerto de Ezeiza",
  "Omar googlee las últimas reviews de Arajet en el gate de embarque como última verificación",
  "Adriana se emocione al ver el mar turquesa desde la ventanilla y bloquee la vista 2 horas",

  // ═══════════════════════════════════════════════════════════════
  // FAMILIAS COMBINADAS / GENERAL (~30)
  // ═══════════════════════════════════════════════════════════════
  "19 personas intenten ponerse de acuerdo para una sola foto grupal decente",
  "la familia necesite juntar 3 mesas para poder cenar todos juntos en el restaurante",
  "el resort aprenda por las malas que los argentinos viajamos siempre en manada",
  "Alejandro proponga dividir la cuenta de algo y todos le recuerden que es all-inclusive",
  "la familia haga más ruido que la animación oficial del hotel",
  "19 personas intenten elegir una excursión grupal y terminen todos en la pileta como siempre",
  "la familia ocupe un sector completo de la playa como si fuera territorio argentino",
  "Pichi se pierda en el resort y 18 personas salgan a buscarlo como operativo policial",
  "la familia haga una videollamada a Marcela desde la playa solo para mostrarle lo que se pierde",
  "19 argentinos descubramos que en el Caribe no hay mate pero hay felicidad all-inclusive",
  "la familia se acuerde de este viaje como el mejor de toda la vida",
  "Silvia se emocione viendo a 4 generaciones de la familia juntas en una playa del Caribe",
  "la familia entera se queme el primer día porque nadie le hizo caso a Stella con el protector",
  "19 personas logren coordinarse para una excursión sin que sea un completo desastre logístico",
  "la familia convierta el restaurante del hotel en una mesa de Navidad argentina",
  "Sebastian diga '¿y si el año que viene repetimos?' al segundo día del viaje",
  "la foto grupal en la playa de Punta Cana se convierta en la foto familiar más épica de la historia",
  "la familia entera se duerma en las reposeras después del almuerzo como Daniel en la siesta",
  "Daniel se pierda el show nocturno del hotel porque se quedó dormido de la comilona",
  "19 personas descubramos oficialmente que somos la familia más ruidosa del Palladium",
  "la familia grabe un video para el grupo de WhatsApp que dure más de 47 minutos",
  "Nani proponga hacer una actividad deportiva y todos terminen en la barra VIP",
  "la familia necesite una logística de mudanza para ir del hotel a la playa con los 19",
  "19 argentinos exportemos el concepto del asado como patrimonio cultural al Palladium",
  "Silvia diga 'la próxima traemos a toda la familia' y todos miremos la silla vacía de Marcela",
  "la familia pose para más fotos grupales que en un casamiento completo",
  "Daniel se duerma en el lobby esperando a que los 18 restantes se terminen de preparar",
  "la familia descubra que 9 noches all-inclusive no son suficientes para hacer todo lo planeado",
  "Silvia llore genuinamente en el aeropuerto de vuelta porque no quiere volver a la realidad",
  "19 personas en 4 generaciones demuestren que la felicidad es un all-inclusive familiar en Punta Cana",

  // ═══════════════════════════════════════════════════════════════
  // "LAS PRIMAS" — SILVIA, SANDRA Y STELLA (~20)
  // ═══════════════════════════════════════════════════════════════
  "'Las Primas' salgan a recorrer el resort como si tuvieran 20 años y cero responsabilidades",
  "'Las Primas' se pidan cocktails con nombres ridículos y se saquen selfies como quinceañeras",
  "Silvia, Sandra y Stella se autoproclemen 'Las Primas' delante de todo el hotel",
  "'Las Primas' copen la barra del lobby como si fuera la previa de un boliche en los 90",
  "'Las Primas' se vistan combinadas para la cena y hagan una entrada triunfal al restaurante",
  "Silvia, Sandra y Stella se escapen del grupo familiar para tener su 'salida de primas'",
  "'Las Primas' se pongan a bailar bachata en la playa y arrastren a los maridos que no quieren",
  "'Las Primas' hagan un brindis cada noche diciendo 'por nosotras, que no envejecemos'",
  "Silvia, Sandra y Stella se adueñen de tres reposeras VIP y las declaren 'zona de primas'",
  "'Las Primas' se hagan un shooting de fotos grupal como si fuera una producción de revista",
  "'Las Primas' le digan a todo el mundo 'somos primas' como si fuera un título nobiliario",
  "Silvia, Sandra y Stella se den cuenta de que juntas son más peligrosas que sus hijos",
  "'Las Primas' organicen una noche de chicas que termine peor que la de Bruno, Nani y Sebastian",
  "'Las Primas' se pongan a cantar en el karaoke del resort y no suelten el micrófono",
  "Silvia, Sandra y Stella se prometan que este viaje es 'el primero de muchos de Las Primas'",
  "'Las Primas' cierren el sport bar del hotel a las 3 AM y los maridos ni se enteren",
  "'Las Primas' se autoproclemen la mejor mesa del restaurante por derecho de antigüedad",
  "Silvia, Sandra y Stella le enseñen a Francesca y Sofi lo que es una verdadera noche de primas",
  "'Las Primas' hagan más escándalo en la pileta que Valentino y Juli juntos",
  "'Las Primas' se olviden la edad real y se comporten como en los veranos de San Clemente",

  // ═══════════════════════════════════════════════════════════════
  // STELLA TREMENDISTA (~15)
  // ═══════════════════════════════════════════════════════════════
  "Stella diga 'nos vamos a morir todos' porque vio una nube gris en el horizonte",
  "Stella grite '¡es dengue!' por una picadura de mosquito común y silvestre",
  "Stella le diga a todos que leyó que el Caribe se está hundiendo y este podría ser el último viaje",
  "Stella anuncie que la corriente marina es 'mortal hoy' porque el agua le llegó a las rodillas",
  "Stella se convenza de que tiene insolación porque le duele la cabeza después de 4 cocktails",
  "Stella diga 'presiento algo malo' cada vez que Omar mencione el clima",
  "Stella llame al médico del hotel porque la arena le hizo un granito en el pie",
  "Stella le diga a Pichi que no coma del buffet porque 'tiene cara de estar en mal estado'",
  "Stella convierta un calambre de pileta en una emergencia médica de nivel 5",
  "Stella anuncie 'esto no es normal' cada vez que el mar tenga olas de más de 20 centímetros",
  "Stella se autodiagnostique tres enfermedades tropicales distintas en una sola tarde",
  "Stella diga que la habitación tiene un 'olor raro' que seguro es tóxico",
  "Stella le pida al barman que le confirme que el hielo está hecho con agua purificada",
  "Stella se convenza de que el ventilador del techo va a caerse durante la noche",
  "Stella le mande un audio al grupo diciendo 'chicas, ¿no les parece que el avión hacía un ruido raro?'",

  // ═══════════════════════════════════════════════════════════════
  // SPORT BAR 24HS (~15)
  // ═══════════════════════════════════════════════════════════════
  "Sebastian, Bruno y Nani descubran que el sport bar del Palladium abre las 24 horas y no vuelvan más",
  "Bruno diga 'voy al sport bar a ver un partido' y aparezca 6 horas después sin poder explicar nada",
  "Sebastian convierta el sport bar en su oficina personal de 11 PM a 5 AM",
  "Nani diga 'solo voy a ver los highlights' y terminen cerrando el sport bar",
  "Bruno, Nani y Sebastian establezcan una rotación de turnos para que el sport bar nunca quede vacío",
  "el sport bar del Palladium quede bautizado como 'la sucursal argentina' por culpa nuestra",
  "Pamela vaya a buscar a Bruno al sport bar a las 2 AM y lo encuentre explicándole el offside a un alemán",
  "Sebastian pida Sidra 1888 en el sport bar y el barman le diga 'señor, esto es el Caribe'",
  "Bruno y Nani se queden viendo un partido de un deporte que no conocen solo por no irse del bar",
  "Alejandro pida una cerveza en el sport bar sin saber que es gratis y casi llore de emoción",
  "Pichi aparezca en el sport bar, no mire un solo partido, pero se haga amigo de todos los que están",
  "Daniel se escape de la siesta de Silvia y lo encuentren en el sport bar haciéndose el dormido",
  "el sport bar necesite reponer stock de cerveza por primera vez en la historia del Palladium",
  "Omar vaya al sport bar solo para quejarse de que no pasan fútbol argentino",
  "Sebastian proponga 'una cervecita rápida en el sport bar' y aparezca para el desayuno del día siguiente",

  // ═══════════════════════════════════════════════════════════════
  // DULCE CARAMELO + NANI Y BRUNO (~10)
  // ═══════════════════════════════════════════════════════════════
  "Bruno y Nani se crucen con un animador del Palladium y tengan flashbacks de Dulce Caramelo",
  "Vanesa le grite 'DULCE CARAMELO' a Bruno en medio del show nocturno del hotel",
  "Bruno y Nani vean al animador del resort bailar y se miren con cara de 'ya vivimos esto'",
  "Vanesa le recuerde a Nani la existencia de Dulce Caramelo en el peor momento posible",
  "Bruno intente evitar la zona de animación del hotel por trauma post-Dulce Caramelo",
  "Sebastian cuente la historia de Dulce Caramelo en la cena y Bruno se quiera meter debajo de la mesa",
  "el animador del Palladium le pida a Bruno que suba al escenario y todos griten 'DULCE CARAMELO'",
  "Nani diga 'ese se parece' cada vez que vean un animador del resort y Bruno entre en pánico",
  "Bruno y Nani descubran que el show del Palladium se llama 'Noche Caribeña' y recen que no incluya un Dulce Caramelo 2.0",
  "la familia entera coree 'DULCE CARAMELO' cada vez que Bruno pase cerca de la pista de baile",

  // ═══════════════════════════════════════════════════════════════
  // SANDRA - ALL INCLUSIVE MÁS BARATO (~10)
  // ═══════════════════════════════════════════════════════════════
  "Sandra mande al grupo de WhatsApp 'hay un all-inclusive que sale 500 USD menos y es igual'",
  "Sandra encuentre un resort más barato a 3 semanas del viaje y proponga cambiar todo",
  "Sandra diga 'encontré uno igual pero más barato' por cuarta vez desde que se confirmó el viaje",
  "Sandra compare el Palladium con un hotel random de Booking que tiene 3 estrellas y media",
  "Sebastian le diga a Sandra que ya están todas las reservas pagas y ella siga buscando ofertas",
  "Sandra le pase a Alejandro el link del hotel más barato y él diga 'ves, yo tenía razón'",
  "Sandra googlee 'all inclusive Punta Cana barato' hasta el día antes de embarcar",
  "Sandra diga 'no digo que sea mejor, digo que sale menos' sobre un hotel con pileta desinflable",
  "Sandra le muestre a Silvia el hotel alternativo y Silvia le diga 'Sandra, ya pagamos'",
  "Sandra archive el link del hotel barato 'para el próximo viaje' y todos respiren aliviados",

  // ═══════════════════════════════════════════════════════════════
  // OMAR VARIADOS (no solo clima) (~15)
  // ═══════════════════════════════════════════════════════════════
  "Omar se queje de la fila del check-in como si fuera una violación a los derechos humanos",
  "Omar diga 'en mis tiempos los aviones eran más grandes' sin ninguna evidencia",
  "Omar calcule cuántos litros de protector solar necesitan 19 personas para 9 días y mande la cuenta al grupo",
  "Omar diga 'esto en Argentina no pasa' sobre algo que pasa constantemente en Argentina",
  "Omar mande un resumen ejecutivo del viaje al grupo de WhatsApp que nadie va a leer",
  "Omar se queje de que el tour en catamarán 'no es lo que prometían en el folleto'",

  // ═══════════════════════════════════════════════════════════════
  // ALEJANDRO VARIADOS (disfruta lo gratis) (~10)
  // ═══════════════════════════════════════════════════════════════
  "Alejandro se quede dormido en la reposera con el libro sobre la cara y se queme solo la panza",
  "Alejandro diga 'el año que viene vamos a un camping' y Sandra le diga 'ni en chiste'",
  "Alejandro diga 'para el próximo viaje organizo yo' y nadie le crea ni un segundo",
  "Alejandro le diga a Sandra 'viste que al final el all-inclusive valió la pena' como si él lo hubiera elegido",

  // ═══════════════════════════════════════════════════════════════
  // CREW + FIESTA — MÁS PICANTES (~20)
  // ═══════════════════════════════════════════════════════════════
  "Sebastian vuelva a la habitación a las 7 AM caminando de costado y diga 'el sol ya está lindo'",
  "Bruno se despierte en la reposera de la playa sin recordar cómo llegó ahí",
  "Nani le diga a Vanesa 'volvimos temprano' con los ojos cerrados de sueño a las 11 AM",
  "Sebastian, Bruno y Nani descubran que el fernet se puede tomar con Coca-Cola dominicana y lloren",
  "Bruno se niegue a reconocer que está borracho porque 'son tragos del Caribe y son más suaves'",
  "Nani intente bailar reggaetón y Vanesa lo grabe para chantajearlo el resto del viaje",
  "Sebastian declare que el barman del VIP es su nuevo mejor amigo desde el segundo día",
  "Bruno pierda las llaves de la habitación y jure que las tenía 'hace 5 minutos' (hace 5 horas)",
  "Nani se quede dormido en el jacuzzi y Bruno tenga que sacarlo como a un fideo overcocinado",
  "Sebastian intente pedir un asado en el restaurante a la carta a las 2 AM y el chef le diga que no",
  "Bruno y Nani se reten a ver quién aguanta más shots de tequila y ninguno gane",
  "Sebastian se emocione tanto con el karaoke que cante 3 canciones seguidas y nadie lo pueda parar",
  "Bruno vuelva del sport bar con una camiseta de un equipo que no conoce y sin poder explicar por qué",
  "Nani descubra que los tragos de la barra de la playa son más fuertes y lo descubra demasiado tarde",
  "Sebastian, Bruno y Nani se pierdan la excursión a Isla Saona porque 'pusimos la alarma pero no sonó'",
  "Bruno intente hacer un mortal en la pileta, falle, y Pamela diga 'te lo dije' sin mirarlo",
  "Nani se haga famoso entre los bartenders como 'el argentino que prueba todo'",
  "Sebastian convierta cada cena en una previa y cada previa en una after",
  "Bruno y Nani lleguen al lobby con la misma ropa de ayer y actúen como si nada",
  "Sebastian se haga un amigo brasileño en la barra y termine hablando portuñol toda la noche",

  // ═══════════════════════════════════════════════════════════════
  // VANESA JODONA — MÁS PICANTES (~15)
  // ═══════════════════════════════════════════════════════════════
  "Vanesa le cuente a Silvia con detalle todo lo que hizo Daniel anoche en la barra VIP",
  "Vanesa les avise a todos que 'se canceló la excursión' para que se queden y después diga 'era joda'",
  "Vanesa le mande un audio falso a Bruno haciéndose pasar por la recepción del hotel",
  "Vanesa les diga a los nenes que hay un parque de dinosaurios en el resort para que enloquezcan",
  "Vanesa le ponga picante a escondidas al plato de Sebastian en el buffet",
  "Vanesa le diga a Alejandro que le cobraron algo extra y lo deje sufrir 10 minutos antes de decir la verdad",
  "Vanesa filme a Sebastian comiendo su cuarto plato de buffet y lo suba al grupo con zoom",
  "Vanesa le diga a Stella que el agua de la canilla del hotel 'tiene un color raro' y la vea entrar en espiral",
  "Vanesa organice una falsa tormenta tropical por WhatsApp solo para molestar a Omar",
  "Vanesa le diga a Pamela que Bruno estaba tirándose bombas en la pileta cuando Pamela no estaba",
  "Vanesa les cuente a todos la anécdota más vergonzosa de Nani en el peor momento posible",
  "Vanesa proponga un juego de preguntas personales en la cena y nadie quiera jugar excepto ella",
  "Vanesa le esconda la toalla a Daniel justo cuando sale de la pileta y Silvia la busque por todo el resort",
  "Vanesa se haga pasar por la anfitriona del hotel y les dé indicaciones falsas a otros huéspedes",
  "Vanesa le cuente al grupo el secreto de Bruno que le dijeron 'no cuentes' hace 3 minutos",

  // ═══════════════════════════════════════════════════════════════
  // COMBOS FAMILIARES PICANTES (~25)
  // ═══════════════════════════════════════════════════════════════
  "Silvia persiga a Daniel con protector solar por toda la playa mientras Sandra filma y se muere de risa",
  "Pichi le cuente a un turista italiano que la familia vino desde San Clemente del Tuyú y le explique toda la historia",
  "Omar se queje de algo y Alejandro le diga 'pero hermano, es gratis' y lo deje sin argumento",
  "Pamela y Vanesa se alíen para controlar a Bruno y Nani y fracasen en 10 minutos",
  "Silvia le diga a Vanesa 'sos igualita a tu madre' como el peor insulto posible y Stella se ofenda",
  "Omar y Stella se retroalimenten mutuamente: él con el pronóstico y ella con enfermedades",
  "Pichi haga reír a un grupo de turistas coreanos que no entienden nada pero igual se ríen",
  "Daniel se escape de la siesta, se cruce a Alejandro en el sport bar y se juren secreto mutuo",
  "Francesca y Sofi les hagan una cuenta regresiva a sus padres de cuánto falta para que las dejen ir solas",
  "Stella le pregunte a Omar si es normal que el mar haga olas y Omar le conteste con un monólogo meteorológico",
  "Sandra le diga a Silvia 'vos sos la soga' y Silvia le diga 'y vos la que busca hoteles baratos'",
  "Pichi le haga un chiste al capitán del catamarán y el tour dure media hora más porque no pararon de hablar",
  "Valentino y Juli le tiren agua a Omar mientras revisa el pronóstico en la reposera y le mojen el celular",
  "Bruno, Nani y Sebastian se disfracen para la fiesta temática y Pamela, Vanesa y Silvia se mueran de vergüenza",
  "Alejandro se anote en todas las excursiones gratis del resort y Sandra le diga 'no podemos hacer todas'",
  "Silvia le arme la valija a Sebastian a los 38 años y Sebastian no diga ni mu",
  "Omar le mande a Daniel un artículo sobre los peligros del sol y Daniel ni lo abra porque está durmiendo la siesta",
  "'Las Primas' le ganen al crew de fiesta en cantidad de tragos consumidos una noche y nadie lo pueda creer",
  "Vanesa proponga un partido de vóley familiar y termine en discusión sobre quién hizo trampa",
  "Stella le ponga repelente a Pichi mientras Pichi está hablando con desconocidos sin darse cuenta",
  "Sebastian pida permiso para repetir por quinta vez en el buffet y el mozo le diga 'señor, es all-inclusive, no necesita permiso'",
  "Omar se queje de los precios de las excursiones y Alejandro le recuerde que son gratis con la pulsera VIP",
  "Pamela y Silvia comparen notas sobre cómo controlar a sus respectivos hombres en vacaciones",
  "Valentino le pregunte a Sebastian por qué se sirve tanto y Sebastian le diga 'porque es gratis, Valen'",
  "la familia entera se dé cuenta de que La Baticueva, los colchones en el piso y el Vivero fueron el entrenamiento para el Palladium",

  // ═══════════════════════════════════════════════════════════════
  // ALL-INCLUSIVE / BUFFET — MÁS PICANTES (~20)
  // ═══════════════════════════════════════════════════════════════
  "Bruno descubra que puede pedir room service a las 3 AM y le cambie la vida para siempre",
  "Sebastian se siente a comer en el buffet y el mozo ya le traiga tres platos porque ya lo conoce",
  "Sebastian se lleve una banana del buffet 'para después' y se la encuentre en el bolsillo de la camisa al otro día",
  "19 argentinos hagamos cola en el buffet del desayuno y el chef piense que hay un evento privado",
  "Nani pregunte '¿cuántos restaurantes puedo visitar en una noche?' y la respuesta sea 'todos'",
  "el barman VIP empiece a preparar los tragos de la familia argentina sin que nadie le pida nada",
  "Bruno intente mezclar comida japonesa con comida italiana en el mismo plato y lo defienda con honor",
  "la familia descubra que hay un buffet de medianoche y se reorganice toda la logística del sueño",
  "Sebastian se emocione porque encontró dulce de leche en el buffet y llame a todos por WhatsApp",
  "Daniel se quede dormido esperando la cena porque almorzó demasiado",
  "Bruno pida 'lo mismo de ayer' en el restaurante y el mozo no tenga idea de qué habla",
  "Nani descubra que los mojitos de la playa llevan más ron que los de la barra y tome nota",
  "Sebastian cuente cuántos platos probó en una cena y el número supere los dos dígitos",
  "el personal del resort empiece a llamar a nuestra familia 'los argentinos del buffet'",
  "Sebastian se lleve un plato de postre 'para la habitación' y se lo coma en el ascensor",
  "la familia necesite dos turnos de cena porque no entramos todos en la misma mesa",
  "Sandra descubra el brunch del domingo y diga 'esto es lo mejor que inventó la humanidad'",
  "Bruno y Nani pidan shots después de la cena y el mozo les diga 'señores, esto es un restaurante' sin convicción",
  "la familia haga el check-out con 3 kilos más por persona en promedio",
  "Sebastian diga 'no me entra más nada' a las 3 PM y a las 7 PM esté en el buffet de vuelta",

  // ═══════════════════════════════════════════════════════════════
  // VARIOS — PICANTES Y COMBINADOS (~40)
  // ═══════════════════════════════════════════════════════════════
  "Silvia sugiera una actividad grupal y todos se escondan en sus habitaciones",
  "Pichi le haga un chiste al tipo de seguridad del aeropuerto y Stella casi se desmaye del susto",
  "Vanesa le diga a todos que hay un upgrade gratis y sea completamente mentira",
  "Bruno diga 'yo a la playa no voy hoy' y aparezca en la playa 20 minutos después",
  "Omar se queje de que las olas no están lo suficientemente calmas para nadar",
  "Sebastian organize la mesa del restaurante como si fuera una reunión de directorio",
  "Alejandro descubra la tienda libre de impuestos del aeropuerto y compre de todo porque 'mirá los precios'",
  "Valentino pregunte en voz alta '¿por qué tío Seba come tanto?' en medio del buffet silencioso",
  "Silvia le arme a Daniel un horario de vacaciones más estricto que un horario laboral",
  "Sandra le mande a Alejandro otro link de hotel barato y él le diga 'Sandra, ya estamos acá'",
  "Pichi intente entrar al kids club a animar a los nenes y el personal no sepa si dejarlo",
  "Stella confunda una iguana del resort con un 'animal peligroso no identificado'",
  "Bruno y Sebastian compitan por quién come más empanadas en una sentada y ambos se arrepientan",
  "Nani se haga pasar por DJ en la fiesta de la pileta y nadie lo frene",
  "Francesca le diga a Pamela 'mamá, por favor no bailes' en público",
  "Omar le diga a Flor que el vuelo de vuelta tiene más turbulencia según su análisis personal",
  "Silvia les ponga horario de volver a la habitación a todos como si tuvieran 15 años",
  "Vanesa convenza a la familia de hacer un flash mob en la playa que salga horrible",
  "Alejandro descubra que la excursión incluye almuerzo y de repente le parezca buena idea",
  "Stella lleve su propio jabón antibacterial porque 'no confía en el del hotel'",
  "Sebastian le diga al chef del restaurante que en Argentina se cocina mejor y el chef lo ignore con dignidad",
  "'Las Primas' se peleen por quién se queda con la mejor reposera y termine interviniendo el guardavidas",
  "Pichi invite a toda una excursión de desconocidos a la cena familiar y nadie se anime a decirle que no",
  "Omar googlee '¿es seguro comer mariscos en República Dominicana?' antes de cada cena",
  "Bruno se tire una bomba tan grande en la pileta que Pamela finja que no lo conoce",
  "Valentino y Juli hagan una competencia de gritos en la playa y gane Juli por lejos",
  "Sebastian descubra que el all-inclusive incluye clases de bachata y se anote con el nombre falso",
  "Silvia le diga a Daniel 'vos no tomás más' y Daniel ya esté pidiendo otro trago con la mirada",
  "Nani y Bruno intenten hacerle una broma a Vanesa y Vanesa les devuelva una peor en 5 minutos",
  "la familia entera intente irse del resort a hacer una excursión y tarden 2 horas en juntarse los 19",
  "Sofi le pida a Sebastian que le saque 'solo una foto más' por séptima vez en la misma pose",
  "Stella le pregunte al médico del hotel si es normal sentirse 'demasiado relajada' en vacaciones",
  "Pichi se haga viral en el TikTok de otro huésped por un chiste que hizo en la pileta",
  "Sandra diga 'yo el año que viene encuentro algo mejor' y todos le griten '¡NO!'",
  "Sebastian, Bruno y Nani le enseñen el himno argentino al barman y él lo cante mejor que ellos",
  "Silvia, Sandra y Stella organicen una sesión de fotos de 'Las Primas' que dure más que la excursión",
  "toda la familia se emocione viendo el atardecer caribeño y Omar lo arruine diciendo que mañana llueve",
  "los 19 nos miremos en la foto grupal y digamos 'de San Clemente a Punta Cana, mirá lo que somos'",
  "este viaje se convierta en la historia que contemos en cada reunión familiar de acá a la eternidad",

  // ═══════════════════════════════════════════════════════════════
  // ANÉCDOTAS REALES + EXTRAS
  // ═══════════════════════════════════════════════════════════════
  "Sebastian y Bruno repitan el operativo carpa de Mar del Plata: pasar caminando de a uno haciéndose los que no se conocen",
  "Sebastian y Bruno se miren de lejos en la playa del Palladium y finjan no conocerse como cuando se colaron en la carpa",
  "Sebastian arme un plan para meter 20 personas en una carpa VIP del resort como hizo en Mar del Plata",
  "Bruno pase caminando por la carpa con cara de nada y Sebastian entre por el otro lado silbando, como en Mardel",
  "Sebastian y Bruno le enseñen a Nani la técnica de 'no nos conocemos' para colarse en cualquier lado",
  "Pichi cuente la historia de la carpa de Mar del Plata en el Palladium y todos los argentinos se mueran de risa",
  "Sebastian y Bruno intenten colarse en la zona premium de la playa haciéndose los que no se conocen y Vanesa los delate gritando sus nombres",
  "Bruno diga 'yo no lo conozco' señalando a Sebastian que está al lado comiendo del mismo plato",
  "Sebastian planee el operativo Palladium VIP con la misma seriedad que el operativo carpa de Mardel",
  "los hombres recuerden la cena en Manolo en Mar del Plata como 'la mejor cena de la historia' y las mujeres como 'el peor restaurante'",
  "los hombres pidan mariscos en el Palladium felices de la vida y las mujeres se quejen de la temperatura del plato, la iluminación y el viento",
  "los hombres digan 'qué buena onda el mozo' y las mujeres digan 'tardó 3 minutos, inaceptable'",
  "Daniel, Omar, Alejandro, Bruno, Nani y Sebastian cenen juntos en paz total y las mujeres en la misma mesa discutan todo",
  "los hombres digan 'estuvo increíble' y las mujeres digan 'estuvo bien, pero...' de la misma exacta cena",
  "los hombres aplaudan al chef del Palladium y las mujeres pidan hablar con el gerente",
  "Sebastian y Bruno se miren cómplices cada vez que haya que colarse en algo y digan 'como en Manolo... digo, como en Mardel'",
  "Vanesa se haga la distraída y termine en la excursión equivocada con un grupo de dominicanos",
  "Vanesa 'se pierda' en la playa y aparezca media hora después charlando con un instructor de buceo dominicano",
  "Nani busque a Vanesa por todo el resort y la encuentre tomando un coctel con un grupo de locales que no hablan español",
  "Vanesa diga 'me confundí de excursión' con una sonrisa sospechosa y Nani no le crea ni medio segundo",
  "Vanesa se anote en la clase de merengue solo porque el instructor es dominicano y Nani la mire desde la reposera",
  "Vanesa diga 'estaba pidiendo indicaciones' al dominicano con el que estuvo charlando 40 minutos",
];
