// ~500 chistes personalizados para la cuenta regresiva.
// Cada string es lo que va después de "Faltan X días para que".
// El componente arma: "Faltan {daysLeft} días para que {joke}"

export const JOKES: string[] = [
  // ═══════════════════════════════════════════════════════════════
  // SILVIA AGUAFIESTAS + SIESTA DANIEL (~50)
  // ═══════════════════════════════════════════════════════════════
  "Silvia arme un Excel con los horarios de siesta de Daniel en el Palladium",
  "Daniel descubra que en el Caribe también hay siestas obligatorias de 2 a 5",
  "Silvia le ponga protector solar factor 100 a Daniel mientras duerme bajo una palmera",
  "Silvia le ate la soga al cuello a Daniel con la pulsera del all-inclusive",
  "Daniel intente escaparse de la siesta y Silvia lo encuentre en la barra VIP",
  "Silvia organice un itinerario de siestas más detallado que el del hotel",
  "Daniel sueñe que está libre y se despierte en la reposera del Palladium con Silvia al lado",
  "Silvia diga 'no exageren con los tragos' a las 11 de la mañana",
  "Daniel pida un mojito y Silvia le cambie el pedido por un jugo de naranja",
  "Silvia prohíba bailar después de las 10 PM porque 'mañana hay que madrugar para el buffet'",
  "Daniel intente pedir una segunda ronda y Silvia lo fulmine con la mirada",
  "Silvia lleve un despertador al Caribe para que Daniel no se pierda el desayuno",
  "Daniel descubra que 'vacaciones' y 'siesta obligatoria' son sinónimos según Silvia",
  "Silvia se queje de la música de la pileta mientras Daniel intenta dormir la siesta",
  "Daniel intente hacer snorkel y Silvia lo mande a descansar primero",
  "Silvia traiga pantuflas de viaje para que Daniel duerma cómodo en cualquier reposera",
  "Daniel confunda el spa con la sala de siesta oficial de Silvia",
  "Silvia le pida al hotel que bajen el aire de la habitación para la siesta perfecta",
  "Daniel proponga salir de noche y Silvia diga 'después de la siesta de mañana hablamos'",
  "Silvia sea la única persona que lleve un antifaz para dormir al Caribe",
  "Daniel duerma más horas de siesta que horas de playa en todo el viaje",
  "Silvia le arme a Daniel un nidito de toallas en la reposera como si tuviera 5 años",
  "Daniel proponga una salida nocturna y Silvia le recuerde que mañana hay siesta temprano",
  "Silvia cronometre las siestas de Daniel para asegurarse de que duerma lo suficiente",
  "Daniel intente hacerse el dormido para que Silvia lo deje en paz un rato",
  "Silvia le explique al personal del hotel que Daniel necesita silencio absoluto entre 2 y 5",
  "Daniel descubra que la pulsera VIP no incluye exención de siestas obligatorias",
  "Silvia arme un grupo de WhatsApp solo para coordinar horarios de siesta",
  "Daniel use más la cama del hotel que la playa, la pileta y los restaurantes combinados",
  "Silvia le reserve a Daniel la reposera más alejada del parlante de la animación",
  "Daniel se pierda tanto la siesta como la cena por quedarse dormido fuera de horario",
  "Silvia diga '¿ya dormiste?' más veces que '¿te pusiste protector?'",
  "Daniel intente escaparse a la barra durante la siesta y el GPS interno de Silvia lo detecte",
  "Silvia convierta la suite junior en una clínica del sueño certificada",
  "Daniel sueñe que está tomando un daiquiri y se despierte abrazando una almohada",
  "Silvia le diga a Sandra 'tu hermana es la reina de las siestas del Palladium'",
  "Daniel descubra que otros maridos también duermen siesta, pero por voluntad propia",
  "Silvia haga un tour por el resort buscando el lugar más silencioso para la siesta",
  "Daniel acumule más horas de sueño que todos los demás viajeros juntos",
  "Silvia le pida al concierge una habitación con triple aislamiento acústico",
  "Daniel vuelva de Punta Cana más descansado que después de un retiro espiritual",
  "Silvia mande a callar a los nenes porque 'Daniel está durmiendo la siesta'",
  "Daniel intente socializar en la pileta y Silvia aparezca con la almohada bajo el brazo",
  "Silvia confunda 'all-inclusive' con 'all-inclusive de siestas para Daniel'",
  "Daniel aprenda a dormir con los ojos abiertos para que Silvia crea que está despierto",
  "Silvia le deje una nota en la reposera: 'Vuelvo en 2 horas. No te muevas. Dormí.'",
  "Daniel descubra que el spa tiene una cama más cómoda que la de la suite junior",
  "Silvia organice un campeonato familiar de siestas y Daniel gane todos los días",
  "Daniel intente hacer una excursión y Silvia diga 'primero la siesta, después vemos'",
  "Silvia sea nombrada Directora Honoraria de Siestas del Grand Palladium Select Bavaro",

  // ═══════════════════════════════════════════════════════════════
  // OMAR TORMENTAS + ARAJET (~35)
  // ═══════════════════════════════════════════════════════════════
  "Omar revise AccuWeather por décima vez buscando la tormenta tropical que arruine todo",
  "Omar mande un PDF al grupo de WhatsApp sobre la temporada de huracanes en el Caribe",
  "Omar calcule la probabilidad exacta de un huracán categoría 5 para el 27 de octubre",
  "Omar se queje de que Arajet no da ni un maní en el vuelo",
  "Omar googlee 'accidentes Arajet 2026' y comparta los resultados en el grupo familiar",
  "Omar descubra que en Arajet el asiento reclinable es un concepto filosófico",
  "Omar le explique a todos que las low cost no tienen los mismos estándares de seguridad",
  "Omar lleve un chaleco salvavidas propio al avión por si acaso",
  "Omar revise la ruta del huracán en tiempo real desde el celular en pleno vuelo de Arajet",
  "Omar se queje de que el espacio entre asientos de Arajet fue diseñado para hobbits",
  "Omar mande capturas del radar meteorológico al grupo a las 3 de la mañana",
  "Omar diga 'yo avisé' cuando caigan dos gotas de lluvia en Punta Cana",
  "Omar lleve un anemómetro personal a las vacaciones",
  "Omar pida cambiar de aerolínea faltando 3 días para el viaje",
  "Omar googlee '¿es seguro viajar a Punta Cana en octubre?' por centésima vez",
  "Omar se queje de que el equipaje de mano en Arajet es del tamaño de una cartera",
  "Omar compare los índices de seguridad de Arajet con los de Aerolíneas Argentinas sin ironía",
  "Omar le muestre a todos una app de rastreo de huracanes en la cena familiar",
  "Omar intente contratar un seguro específico contra huracanes categoría 3 o superior",
  "Omar le pregunte al piloto de Arajet si revisó bien el avión antes de despegar",
  "Omar saque estadísticas de por qué octubre es el peor mes para ir al Caribe",
  "Omar se queje del tamaño de la bandeja de Arajet como si fuera un crimen de lesa humanidad",
  "Omar descubra que 'low cost' también aplica al aire acondicionado del avión",
  "Omar proponga llevar comida de casa porque 'en Arajet no te dan nada'",
  "Omar le diga a Adriana que se despida del barrio por las dudas",
  "Omar investigue las rutas de evacuación del hotel en caso de huracán",
  "Omar pregunte en recepción del Palladium si el resort tiene búnker anti-huracanes",
  "Omar revise el pronóstico extendido a 45 días como si fuera un meteorólogo profesional",
  "Omar mande un audio de 5 minutos explicando por qué Arajet es peor que un colectivo",
  "Omar le pida a Sebastian que cambie los pasajes a American Airlines a último momento",
  "Omar descubra que la turbulencia en Arajet es una feature, no un bug",
  "Omar traiga un barómetro de viaje en la valija",
  "Omar se queje de que ni siquiera dan una galletita de agua en el vuelo",
  "Omar calcule que por el precio de Arajet les conviene ir nadando hasta Punta Cana",
  "Omar se agarre del apoyabrazos en cada turbulencia y le rece a tres santos distintos",

  // ═══════════════════════════════════════════════════════════════
  // SEBASTIAN SIDRA / BUFFET / FIESTA (~40)
  // ═══════════════════════════════════════════════════════════════
  "Sebastian descubra que la Sidra 1888 no está en el all-inclusive y tenga que conformarse con champagne",
  "Sebastian se llene 4 platos en el buffet y diga 'es que estoy flaco, me lo puedo permitir'",
  "Sebastian pregunte en la barra VIP si tienen Sidra 1888 importada desde Argentina",
  "Sebastian arme una torre de comida en el plato que desafíe las leyes de la gravedad",
  "Sebastian declare que el all-inclusive es su disciplina olímpica",
  "Sebastian vuelva al buffet por quinta vez diciendo 'solo voy a buscar el postre'",
  "Sebastian intente despachar una botella de Sidra 1888 como equipaje frágil",
  "Sebastian haga un brindis con lo que sea que tenga en la mano, aunque sea agua",
  "Sebastian calcule cuántos platos de buffet necesita comer para amortizar el viaje entero",
  "Sebastian descubra que puede repetir infinitas veces en el buffet y llore de emoción",
  "Sebastian llene el plato como si fuera la última cena de su vida",
  "Sebastian diga 'este buffet me necesita a mí' en vez de 'yo necesito este buffet'",
  "Sebastian investigue si el all-inclusive cubre el cuarto almuerzo del día",
  "Sebastian haga competencia de platos llenos con Bruno y Nani en el buffet",
  "Sebastian intente explicarle a un bartender dominicano qué es la Sidra 1888",
  "Sebastian diga 'estoy probando de todo' mientras repite el mismo plato por sexta vez",
  "Sebastian cierre la barra VIP a las 4 AM y abra el buffet del desayuno sin pasar por la cama",
  "Sebastian proponga 'un brindis' cada 20 minutos hasta que se quede sin excusas",
  "Sebastian descubra el buffet de medianoche y no vuelva a ser la misma persona",
  "Sebastian lleve pantalones con elástico 'por las dudas' al viaje",
  "Sebastian convierta el minibar de la habitación en su bodega personal de Sidra 1888",
  "Sebastian haga un ranking exhaustivo de los 7 restaurantes del resort",
  "Sebastian pida un waiver oficial para el límite de platos por persona en el buffet",
  "Sebastian termine el viaje pesando exactamente igual porque su metabolismo es injusto",
  "Sebastian descubra que hay 7 restaurantes y quiera cenar en todos en una sola noche",
  "Sebastian use más el buffet que la playa, la pileta y el spa combinados",
  "Sebastian se pare en la fila del buffet 10 minutos antes de que abra",
  "Sebastian invente un coctel que combine champagne con algo que se parezca a la 1888",
  "Sebastian se haga amigo del chef del buffet para pedirle porciones extra",
  "Sebastian descubra el room service a las 3 AM y considere no salir más de la suite",
  "Sebastian proponga 'una última copa' por decimoséptima vez en la noche",
  "Sebastian apile sushi, pasta y carne en el mismo plato y lo llame 'fusión argentina'",
  "Sebastian calcule cuántas calorías por dólar consume en el all-inclusive",
  "Sebastian le gane un mano a mano al buffet del Palladium",
  "Sebastian tenga un sexto sentido para detectar cuándo reponen un plato nuevo",
  "Sebastian haga un álbum de fotos dedicado exclusivamente a sus platos del buffet",
  "Sebastian confunda el restaurante japonés con el buffet libre y pida 'de todo un poco'",
  "Sebastian necesite dos reposeras: una para él y otra para la digestión post-buffet",
  "Sebastian vuelva de Punta Cana sin un gramo de más y todos lo odien injustamente",
  "Sebastian intente convencer al barman de que la Sidra 1888 es una bebida premium internacional",

  // ═══════════════════════════════════════════════════════════════
  // VANESA JODONA (~35)
  // ═══════════════════════════════════════════════════════════════
  "Vanesa le esconda la toalla a alguien en la playa y se haga la desentendida",
  "Vanesa le cambie el protector solar a alguien por bronceador sin avisar",
  "Vanesa ponga una alarma a las 6 AM en el celular de otra persona dormida",
  "Vanesa le mueva la reposera a Daniel mientras duerme la siesta y lo deje al sol",
  "Vanesa le diga a Silvia que Daniel está en la barra en vez de durmiendo",
  "Vanesa le ponga arena en las ojotas a Bruno cuando no esté mirando",
  "Vanesa convenza a Valentino y Juli de que hay tiburones en la pileta",
  "Vanesa le pida al DJ que ponga reggaetón a todo volumen cuando todos quieren dormir",
  "Vanesa esconda las llaves de la habitación de alguien y se haga la inocente",
  "Vanesa le saque fotos dormidos a todos para subirlas al grupo de WhatsApp",
  "Vanesa le diga a Omar que vio una nube sospechosa en el horizonte y lo mire disfrutar",
  "Vanesa le cambie el idioma del celular a alguien al mandarín",
  "Vanesa le cuente a Stella que el agua del resort puede tener bacterias exóticas",
  "Vanesa invente que hay una actividad obligatoria a las 7 AM y despierte a todos",
  "Vanesa le diga a Sebastian que el buffet cerró temprano solo para verle la cara",
  "Vanesa le tire agua a alguien dormido en la reposera y salga corriendo",
  "Vanesa le ponga un cangrejo de plástico en la cama de la suite de alguien",
  "Vanesa le diga a Alejandro que el minibar no es gratis para ver su expresión de terror",
  "Vanesa organice un karaoke obligatorio sin el consentimiento de nadie",
  "Vanesa grabe los mejores videos vergonzosos del viaje para el grupo familiar",
  "Vanesa le diga a Pichi que un huésped se ofendió con su último chiste",
  "Vanesa le cambie la reserva del restaurante a otra fecha sin avisar",
  "Vanesa convenza a todos de ir a una excursión a las 6 AM después de una noche de fiesta",
  "Vanesa le diga a Silvia que vio a Daniel tomando tragos a escondidas durante la siesta",
  "Vanesa le esconda el botiquín a Stella y disfrute el caos hipocondríaco",
  "Vanesa invente un rumor sobre una fiesta temática de disfraces obligatoria",
  "Vanesa le ponga el despertador a las 5 AM a Sebastian después de cerrar la barra",
  "Vanesa proponga un juego de verdad o reto en la pileta que nadie pidió",
  "Vanesa le cuente a Omar que leyó sobre un terremoto reciente en República Dominicana",
  "Vanesa le mueva las cosas de la habitación de alguien mientras están en la playa",
  "Vanesa publique las peores fotos de todos en sus stories de Instagram",
  "Vanesa le diga a Roque que el agua de la pileta está helada para verlo dudar",
  "Vanesa organice una broma grupal contra Sebastian coordinando a los nenes",
  "Vanesa le cambie el ringtone del celular a Daniel por un canto de gallo",
  "Vanesa convenza a Valentino y Juli de despertar a todos tirándoles almohadas",

  // ═══════════════════════════════════════════════════════════════
  // BRUNO / NANI / SEBA CREW FIESTA (~40)
  // ═══════════════════════════════════════════════════════════════
  "Bruno, Nani y Sebastian cierren la barra VIP a las 4 AM por tercera noche consecutiva",
  "Bruno, Nani y Sebastian descubran que el all-inclusive tiene barra 24 horas y se les iluminen los ojos",
  "Bruno, Nani y Sebastian hagan un pacto sagrado de no dormirse antes de las 5 AM",
  "Sebastian le proponga a Bruno y Nani 'una última copa' por vigésima vez en la noche",
  "Bruno intente hacer bomba en la pileta a las 2 AM mientras Nani filma",
  "Nani desafíe a Bruno a ver quién toma más mojitos en una hora",
  "Sebastian, Bruno y Nani se pierdan el desayuno por tercera vez consecutiva",
  "Bruno haga un brindis individual por cada uno de los 19 miembros de la familia",
  "Nani se haga tan amigo del barman que le sirvan tragos off-menu",
  "Sebastian, Bruno y Nani aparezcan al desayuno con lentes de sol y sin capacidad de habla",
  "Bruno descubra que la disco del hotel existe y desaparezca por horas",
  "Nani proponga ir a un club nocturno en Bávaro y volver justo para el desayuno",
  "Sebastian, Bruno y Nani tengan su propia mesa VIP reservada en la barra todas las noches",
  "Bruno convierta cualquier rincón del resort en una pista de baile improvisada",
  "Nani descubra las fiestas de espuma del hotel y las declare su lugar feliz",
  "Sebastian le enseñe a los bartenders dominicanos a hacer fernet con coca",
  "Bruno, Nani y Sebastian aprendan a bailar bachata después del tercer trago",
  "Nani se quede dormido en la reposera de la playa y se despierte al amanecer",
  "Bruno intente convencer a Pamela de que anoche volvió temprano a la habitación",
  "Sebastian cierre la disco y abra el desayuno sin pasar por la habitación en ningún momento",
  "Bruno y Nani descubran que en el VIP los tragos vienen dobles automáticamente",
  "Sebastian proponga 'solo una copa antes de dormir' a las 2 AM con total seriedad",
  "Bruno, Nani y Sebastian inventen un coctel nuevo y le pongan un nombre argentino épico",
  "Nani se quede bailando solo en la pista cuando Bruno y Sebastian ya se fueron a dormir",
  "Bruno haga karaoke a las 3 AM y despierte a medio piso del hotel",
  "Sebastian, Bruno y Nani compitan por quién conoce más gente nueva en una noche",
  "Bruno diga 'esta es la mejor noche de mi vida' absolutamente todas las noches",
  "Nani proponga ir a la playa de noche 'solo para ver las estrellas' con un trago en la mano",
  "Sebastian, Bruno y Nani lleguen a la habitación justo cuando otros salen a desayunar",
  "Bruno intente tirarse a la pileta de noche y Pamela lo agarre del brazo a último segundo",
  "Nani se quede dormido en un sillón del lobby esperando a que los demás se preparen",
  "Sebastian invite a un grupo de desconocidos a tomar shots con la familia argentina",
  "Bruno descubra el minibar de la suite VIP y considere seriamente no salir de la habitación",
  "Sebastian, Bruno y Nani se pierdan la excursión del día siguiente por culpa de la resaca",
  "Nani haga más amigos en la barra en una noche que Pichi en todo el viaje",
  "Bruno proponga 'repetir la noche anterior pero más tranqui' y termine exactamente igual",
  "Sebastian tome champagne como si fuera Sidra 1888 y nadie note la diferencia",
  "Bruno, Nani y Sebastian vuelvan con más fotos en la barra que en la playa",
  "Nani descubra que el DJ del hotel acepta pedidos y no lo deje en paz toda la noche",
  "Sebastian, Bruno y Nani calculen que durmieron un total de 15 horas entre los tres en 9 noches",

  // ═══════════════════════════════════════════════════════════════
  // ROQUE - SUTILES (~20)
  // ═══════════════════════════════════════════════════════════════
  "Roque encuentre la mejor reposera del resort antes que todos cada mañana",
  "Roque se haga amigo del jardinero del Palladium en los primeros 15 minutos",
  "Roque se levante a las 6 AM y tenga la pileta entera para él solo",
  "Roque sea el primero en la fila del buffet del desayuno cada día sin excepción",
  "Roque elija la silla más cómoda del lobby y la haga oficialmente suya por 9 días",
  "Roque conozca cada rincón del resort mejor que el personal después de 48 horas",
  "Roque encuentre un rincón tranquilo que ningún otro huésped haya descubierto",
  "Roque sea el único que se levante descansado y renovado todos los días del viaje",
  "Roque le explique a Valentino cómo se viajaba cuando él era chico",
  "Roque tenga su propia rutina de resort completamente independiente y perfeccionada",
  "Roque sea el primero en probar cada restaurante nuevo del hotel",
  "Roque haga más amigos entre el personal del resort que todos los demás juntos",
  "Roque descubra el rincón de lectura del Palladium y establezca residencia permanente ahí",
  "Roque se adapte al ritmo caribeño más rápido que cualquier millennial del grupo",
  "Roque tenga el bronceado más parejo del grupo sin hacer el más mínimo esfuerzo",
  "Roque descubra que el all-inclusive incluye café expresso de verdad y declare que está en el cielo",
  "Roque sea la única persona genuinamente relajada del grupo durante los 9 días completos",
  "Roque encuentre la hamaca perfecta entre dos palmeras y la defienda con honor",
  "Roque se despierte con el sol caribeño y diga 'esto sí es vida' todas las mañanas",
  "Roque camine más kilómetros recorriendo el resort que cualquier excursión organizada",

  // ═══════════════════════════════════════════════════════════════
  // VALENTINO Y JULI - NENES (~30)
  // ═══════════════════════════════════════════════════════════════
  "Valentino y Juli conviertan la pileta de adultos en un parque acuático no autorizado",
  "Valentino tire una bomba en la pileta que moje a medio hotel incluyendo las reposeras",
  "Juli le grite '¡mirá papi!' a Nani 47 veces por hora sin excepción",
  "Valentino y Juli descubran que el helado del resort es ilimitado y pierdan la cabeza",
  "Valentino persiga cangrejos en la playa hasta que alguien entre en pánico real",
  "Juli quiera bañarse en la pileta a las 7 AM cuando nadie se levantó todavía",
  "Valentino y Juli gasten más energía en una mañana que el generador del hotel en un día",
  "Juli pregunte '¿cuándo llegamos?' cada 5 minutos durante todo el vuelo de Arajet",
  "Valentino descubra los toboganes acuáticos del resort y se niegue a hacer cualquier otra cosa",
  "Juli y Valentino se llenen de arena hasta en lugares anatómicamente imposibles",
  "Valentino pida helado de desayuno, de almuerzo, de merienda y de cena sin negociar",
  "Juli haga un castillo de arena más ambicioso que la suite junior",
  "Valentino y Juli corran por el lobby del hotel como si fuera una cancha de fútbol 5",
  "Juli quiera llevar un cangrejo vivo de mascota en el avión de vuelta",
  "Valentino tire la bomba del siglo en la pileta justo cuando Roque se estaba relajando",
  "Juli y Valentino pregunten '¿hay wifi?' parados en la orilla del mar Caribe",
  "Valentino descubra que puede repetir postre infinitas veces y entre en éxtasis",
  "Juli convenza a Valentino de competir quién aguanta más bajo el agua hasta asustar a todos",
  "Valentino y Juli transformen el buffet de postres en una zona de guerra de servilletas",
  "Juli le pida al barman un coctel 'como el de papá' con total naturalidad",
  "Valentino y Juli descubran los shows nocturnos del hotel y se nieguen a ir a dormir",
  "Valentino le salpique agua a Omar justo cuando está leyendo el pronóstico del tiempo",
  "Juli le pregunte a Stella si las cremas del botiquín son para jugar a los doctores",
  "Valentino y Juli se pierdan en el resort y aparezcan en el spa de adultos",
  "Juli quiera dormir en la reposera de la playa en vez de volver a la habitación",
  "Valentino convierta las duchas de la pileta en un parque de diversiones personal",
  "Juli y Valentino agoten a Pamela y Vanesa antes del mediodía del primer día",
  "Valentino haga amigos con todos los nenes del hotel en los primeros 10 minutos",
  "Juli llore porque el avión de Arajet no tiene pantallita individual",
  "Valentino y Juli tengan más energía a las 10 PM que todos los adultos a las 10 AM",

  // ═══════════════════════════════════════════════════════════════
  // FRANCESCA Y SOFI - TEENS (~25)
  // ═══════════════════════════════════════════════════════════════
  "Francesca y Sofi hagan 400 selfies con el atardecer caribeño y ninguna les guste",
  "Francesca y Sofi evalúen cada rincón del resort por su potencial instagrameable",
  "Sofi pida la contraseña del wifi antes de preguntar dónde queda la playa",
  "Francesca y Sofi le saquen una foto a cada coctel del bar sin probar ninguno",
  "Francesca descubra que el resort tiene sesiones de fotos profesionales incluidas",
  "Sofi diga 'esto lo vi en TikTok' cada vez que alguien proponga cualquier actividad",
  "Francesca y Sofi se hagan amigas de otros adolescentes del resort en 5 minutos exactos",
  "Sofi evalúe los 9 días de viaje basándose exclusivamente en la calidad del wifi",
  "Francesca haga un reel de cada plato del buffet antes de dar el primer bocado",
  "Francesca y Sofi se queden despiertas hasta las 3 AM scrolleando TikTok en la cama",
  "Sofi le enseñe a Roque a usar filtros de Instagram con paciencia infinita",
  "Francesca y Sofi desaparezcan en el club de teens del resort y no las veamos en días",
  "Sofi encuentre el ángulo perfecto para la foto de la pileta después de 47 intentos",
  "Francesca le diga a Pamela que por favor no la etiquete en fotos vergonzosas familiares",
  "Francesca y Sofi hagan más fotos que recuerdos reales durante todo el viaje",
  "Sofi proponga cambiar de restaurante porque la iluminación no es buena para fotos",
  "Francesca descubra que hay actividades organizadas para teens y no vuelvan a ver a sus padres",
  "Sofi diga 'esto queda en mi highlight de Punta Cana' aproximadamente 300 veces",
  "Francesca y Sofi se mueran de vergüenza cuando Pichi hable con sus nuevos amigos del resort",
  "Sofi le explique a Omar cómo funciona el filtro del clima en su celular",
  "Francesca y Sofi consuman más datos móviles que todo el grupo familiar junto",
  "Sofi se queje de que la playa no tiene el color exacto que sale en el folleto",
  "Francesca haga un vlog completo del viaje que probablemente nadie más que ella mire",
  "Francesca y Sofi se resistan a las actividades familiares porque son 'cringe total'",
  "Sofi le pida a Sebastian que le saque una foto 'natural' y le dirija 47 tomas diferentes",

  // ═══════════════════════════════════════════════════════════════
  // ALEJANDRO TACAÑO - SUTIL (~25)
  // ═══════════════════════════════════════════════════════════════
  "Alejandro calcule el costo por minuto del viaje para asegurarse de aprovecharlo al máximo",
  "Alejandro pregunte si el all-inclusive incluye absolutamente todo... por segunda vez",
  "Alejandro guarde un snack del avión de Arajet 'por si acaso lo necesita después'",
  "Alejandro calcule cuántos tragos necesita tomar por día para amortizar la membresía VIP",
  "Alejandro sugiera llevar comida del buffet a la habitación para ahorrar el snack nocturno",
  "Alejandro pregunte si hay descuento por quedarse un día más en el Palladium",
  "Alejandro revise la cuenta del minibar aunque le digan mil veces que es all-inclusive",
  "Alejandro guarde todos los jaboncitos del hotel en un rincón de la valija",
  "Alejandro calcule cuánto ahorraron con la promo BIGDAYS en dólares, pesos y unidades de milanesa",
  "Alejandro traiga bolsitas ziplock para guardar fruta del buffet del desayuno",
  "Alejandro pregunte si las excursiones están incluidas o si hay que pagar extra",
  "Alejandro compare mentalmente el precio del resort con cuánto gastaría en San Clemente",
  "Alejandro se lleve los shampoos, acondicionadores y gorritos de baño del hotel cada día",
  "Alejandro tome nota mental de cada centavo que gasta fuera del all-inclusive",
  "Alejandro pregunte en recepción si hay happy hour aunque todo sea all-inclusive",
  "Alejandro proponga ir a un supermercado local a comprar agua mineral 'que acá es carísima'",
  "Alejandro calcule el costo por metro cuadrado de nadar en la pileta del resort",
  "Alejandro se lleve las pantuflas del hotel como souvenir práctico",
  "Alejandro evalúe si cada actividad del spa vale la pena en una planilla de Excel mental",
  "Alejandro proponga dividir los gastos de las excursiones en partes iguales exactas hasta el centavo",
  "Alejandro traiga protector solar comprado en Argentina porque 'allá sale el doble'",
  "Alejandro use la calculadora del celular más que la cámara durante el viaje",
  "Alejandro pregunte si las toallas de playa del hotel se pueden llevar como souvenir",
  "Alejandro investigue el tipo de cambio del peso dominicano antes de comprar una postal",
  "Alejandro le diga a Sandra que no necesitan el upgrade de habitación, que la estándar está bien",

  // ═══════════════════════════════════════════════════════════════
  // STELLA HIPOCONDRÍACA (~25)
  // ═══════════════════════════════════════════════════════════════
  "Stella meta en la valija un botiquín más grande que toda su ropa junta",
  "Stella le embadurne repelente a todos cada 47 minutos sin preguntar",
  "Stella googlee 'enfermedades tropicales República Dominicana 2026' y le dé un micro-infarto",
  "Stella desinfecte la habitación del hotel de punta a punta antes de deshacer la valija",
  "Stella lleve termómetro, oxímetro, tensiómetro y botiquín de campaña militar",
  "Stella le pregunte al médico del hotel si hubo casos de dengue este mes",
  "Stella revise la fecha de vencimiento de cada cosa que sirvan en el buffet",
  "Stella lleve alcohol en gel para cada bolsillo de cada prenda de cada miembro de la familia",
  "Stella se ponga repelente encima del protector encima del repelente otra vez",
  "Stella pregunte si el agua de la pileta está tratada con la concentración correcta de cloro",
  "Stella investigue cuál es el hospital más cercano al resort y cómo llegar a pie",
  "Stella le diga a todos que no caminen descalzos por la arena porque hay parásitos",
  "Stella desinfecte los cubiertos del restaurante con toallitas aunque estén recién lavados",
  "Stella lleve pastillas para el mareo, el dolor, la alergia, el estómago, el sol y el aburrimiento",
  "Stella le ponga protector solar a Pichi incluso en un día completamente nublado",
  "Stella se autodiagnostique dengue por una picadura de mosquito normal",
  "Stella pregunte si las sábanas del hotel son hipoalergénicas y orgánicas",
  "Stella lleve mascarillas N95 para el vuelo de Arajet 'por el aire recirculado'",
  "Stella sea la única persona que lea el folleto de seguridad del hotel completo dos veces",
  "Stella confunda un bronceado normal con una reacción alérgica grave",
  "Stella tenga el número del médico del hotel guardado como contacto favorito",
  "Stella revise si cada botella de agua del minibar está perfectamente sellada",
  "Stella le diga a Valentino que no toque absolutamente nada sin lavarse las manos primero",
  "Stella lleve un kit de primeros auxilios que pese más que su equipaje de mano",
  "Stella sugiera no ir a la playa un día porque leyó un artículo sobre medusas en el Caribe",

  // ═══════════════════════════════════════════════════════════════
  // PICHI SINVERGÜENZA (~25)
  // ═══════════════════════════════════════════════════════════════
  "Pichi le cuente un chiste malo a un turista alemán que no habla ni una palabra de español",
  "Pichi se haga amigo personal del gerente del Palladium en las primeras 2 horas del check-in",
  "Pichi le haga un chiste al piloto de Arajet mientras embarca y la azafata no sepa qué hacer",
  "Pichi invite a una familia brasileña completa a tomar algo en nuestra mesa",
  "Pichi le cuente su vida entera al taxista del aeropuerto de Punta Cana en el trayecto",
  "Pichi conozca a más huéspedes del resort que el mismísimo personal de recepción",
  "Pichi haga reír a un mozo del restaurante tanto que se le caiga la bandeja",
  "Pichi le pregunte al DJ si puede subir al escenario a cantar una canción con él",
  "Pichi se meta en una conversación ajena en la pileta y termine siendo el protagonista absoluto",
  "Pichi les describa un asado argentino a unos turistas canadienses con detalles épicos",
  "Pichi le diga 'amigo' a un guardia de seguridad que acaba de conocer hace 30 segundos",
  "Pichi le cuente chistes al personal de limpieza todas las mañanas como si fuera stand-up",
  "Pichi organice una peña folclórica improvisada en el lobby del Palladium",
  "Pichi se haga amigo de toda la mesa de al lado en el restaurante antes del primer plato",
  "Pichi le pregunte a un turista francés si sabe lo que es un verdadero asado con cuero",
  "Pichi anime un karaoke en el bar sin que absolutamente nadie se lo haya pedido",
  "Pichi haga avergonzar a Francesca y Sofi delante de sus nuevos amigos adolescentes del resort",
  "Pichi le cuente la historia completa del viaje familiar a cada persona que se cruce",
  "Pichi le haga tantos chistes al barman que le empiecen a servir tragos dobles de simpatía",
  "Pichi transforme una excursión grupal tranquila en su show de stand-up personal",
  "Pichi le diga a un huésped desprevenido que él es parte del staff de entretenimiento del hotel",
  "Pichi haga más contactos en 9 días de vacaciones que un networker en LinkedIn en un año",
  "Pichi tenga más fotos con desconocidos del resort que con su propia familia",
  "Pichi le haga un chiste a alguien en la fila del buffet y termine cenando con ellos",
  "Pichi haga que Stella se tape la cara de vergüenza al menos 3 veces por día",

  // ═══════════════════════════════════════════════════════════════
  // PAMELA VS BRUNO (~15)
  // ═══════════════════════════════════════════════════════════════
  "Pamela le prohíba a Bruno hacer bomba en la pileta del hotel por cuarta vez en el día",
  "Pamela le diga a Bruno que no puede tirarse de cabeza donde dice 'no diving' en inglés",
  "Pamela le ponga protector solar a Bruno como si tuviera 5 años en vez de 30 y pico",
  "Pamela persiga a Bruno por medio resort para que se ponga la remera",
  "Pamela le diga a Bruno 'no hagas escándalo' mientras Bruno está haciendo escándalo",
  "Pamela calcule las horas de sueño que Bruno perdió por salir con Sebastian y Nani",
  "Pamela le mande un mensaje a Bruno a las 3 AM preguntando exactamente dónde está",
  "Pamela le diga a Bruno que se comporte como un adulto responsable frente a Valentino",
  "Pamela encuentre a Bruno haciendo competencias de bomba con Valentino y Juli en la pileta",
  "Pamela descubra que Bruno pasó 3 horas en la barra VIP 'buscando dónde cenar'",
  "Pamela le confisque los shots a Bruno como si fuera su tercer hijo",
  "Pamela le diga 'una más y nos vamos' y Bruno interprete 'una más... y después otra más'",
  "Pamela mire a Bruno con esa cara legendaria cuando hace la bomba número 47 del día",
  "Pamela le explique a Francesca por qué papá está durmiendo a las 2 PM un martes",
  "Pamela le instale un GPS imaginario a Bruno para saber si está en la barra o en la playa",

  // ═══════════════════════════════════════════════════════════════
  // MARCELA - NO VIENE (~15)
  // ═══════════════════════════════════════════════════════════════
  "Marcela no pueda intentar pasar 10 kg de yerba Amanda por la aduana dominicana esta vez",
  "Marcela no esté para exigirle flores frescas al mozo en cada mesa del restaurante",
  "Marcela nos mande un audio de 7 minutos quejándose de que nadie la invitó",
  "Marcela no pueda obligar a las meseras del Palladium a poner centros de mesa florales",
  "Marcela descubra nuestras fotos del viaje en Instagram y se arrepienta de no haber venido",
  "Marcela nos mande la lista completa de todo lo que nos estamos perdiendo por no llevar yerba",
  "extrañemos los mates de Marcela con yerba Amanda en la playa... o quizás no tanto",
  "Marcela no esté para reorganizar la disposición de cada mesa del restaurante a su gusto",
  "Marcela no pueda redecorar la habitación del hotel con arreglos florales improvisados",
  "el grupo entero se acuerde de cuando casi la paran en el aeropuerto por los paquetes de yerba Amanda",
  "Marcela mande fotos de su mate solitario con Amanda desde Argentina mientras nosotros estamos en la playa",
  "ningún mozo del Palladium sea obligado a poner flores en la mesa y pueda trabajar en paz",
  "Marcela pregunte por WhatsApp si estamos tomando mate allá con tono de decepción",
  "nos demos cuenta de que sin Marcela nadie exige decoración floral en la cena",
  "Marcela nos mande un tutorial por WhatsApp de cómo hacer mate con agua del Caribe",

  // ═══════════════════════════════════════════════════════════════
  // SAN CLEMENTE → PUNTA CANA (~20)
  // ═══════════════════════════════════════════════════════════════
  "revivamos los veranos en San Clemente del Tuyú, pero esta vez con pulsera VIP del Palladium",
  "comparemos las olas marrones de San Clemente con el mar turquesa cristalino de Punta Cana",
  "pasemos de los panchos de la playa en San Clemente a langosta en el buffet 5 estrellas",
  "cambiemos los baldazos de agua fría de San Clemente por la pileta climatizada del resort",
  "dejemos atrás las sombrillas rotas de San Clemente por las camas balinesas del Palladium",
  "los nenes experimenten una playa sin las medusas clásicas de San Clemente del Tuyú",
  "pasemos de amontonarnos 8 personas en una habitación a tener suite junior con vista al jardín",
  "cambiemos el Fernet playero de San Clemente por cocktails VIP en el Caribe",
  "dejemos de pelearnos por reposeras en San Clemente y tengamos servicio de toallas premium",
  "pasemos de los helados de palito de San Clemente a los helados artesanales del resort",
  "recordemos cuando la 'excursión familiar' era caminar hasta el faro de San Clemente",
  "cambiemos el protector solar genérico de San Clemente por el protector premium del spa",
  "nos saquemos la foto grupal en el Caribe como la sacábamos en la playa de San Clemente",
  "pasemos de la parrilla del camping a la cena gourmet del Palladium sin escalas",
  "cambiemos la pileta municipal de San Clemente por una infinity pool con vista al mar Caribe",
  "dejemos de contar monedas para el estacionamiento de San Clemente y tengamos all-inclusive",
  "pasemos de San Clemente del Tuyú a Bávaro, Punta Cana, y nadie pueda creerlo",
  "cambiemos el '¿hay agua caliente?' de San Clemente por '¿hay champagne?' en el Palladium",
  "nos demos cuenta de que la familia creció de San Clemente a 5 estrellas en el Caribe",
  "los nenes no tengan idea de lo que es un balneario público gracias a este viaje",

  // ═══════════════════════════════════════════════════════════════
  // ALL-INCLUSIVE / VIP / BUFFET (~40)
  // ═══════════════════════════════════════════════════════════════
  "alguien pregunte '¿el minibar también es all-inclusive?' por quinta vez en el viaje",
  "19 argentinos invadan el buffet del Palladium como si no existiera el mañana",
  "alguien descubra que los tragos VIP son dobles y entre en un estado de gracia permanente",
  "la familia entera aplique la estrategia oficial de 'comer como si no hubiera vuelta'",
  "la pulsera VIP se convierta en la joya más preciada y querida de todo el viaje",
  "alguien arme un plato tan alto en el buffet que necesite escolta hasta la mesa",
  "el personal del buffet reconozca a nuestra familia por la cantidad récord de repeticiones",
  "todos descubramos que 'all-inclusive' es el concepto más hermoso del idioma español",
  "alguien intente meter sushi, pasta, carne y postre en un solo plato y lo logre",
  "la barra VIP del Palladium se quede sin hielo por primera vez en su historia",
  "alguien pregunte '¿puedo llevar comida a la habitación?' con voz bajita y cara de culpa",
  "el barman VIP vea venir a nuestra familia y empiece a preparar tragos antes de que pidamos",
  "alguien descubra el snack bar de las 3 AM y le cambie la vida para siempre",
  "la familia consuma más helado en 9 días que un crucero entero en un mes",
  "alguien se ponga el pijama para ir al buffet de medianoche sin ninguna vergüenza",
  "el chef del Palladium aprenda qué es el dulce de leche argentino gracias a nosotros",
  "la familia pida 'un poquito más por favor' en cada restaurante del resort",
  "descubramos que el VIP del Socio Travel Club valió cada centavo invertido",
  "alguien confunda el lobby bar con su living personal y se instale ahí permanentemente",
  "la familia deje reviews mentales de cada restaurante como si fueran críticos gastronómicos profesionales",
  "la barra VIP necesite un delivery urgente de ron por culpa de nuestra familia",
  "alguien descubra que los cocktails tropicales tienen nombres imposibles de pronunciar",
  "nos deprima genuinamente volver a tener que cocinar después de 9 días de buffet ilimitado",
  "la pulsera all-inclusive genere más felicidad colectiva que cualquier regalo de Navidad",
  "alguien intente llevarse una bandeja entera del buffet como souvenir del viaje",
  "el staff del Palladium cuente la leyenda de la familia argentina de 19 personas durante años",
  "alguien repita el mismo plato 4 veces en la misma cena y diga 'estoy probando variaciones'",
  "la familia argentina demuestre que 19 personas pueden efectivamente vaciar un buffet",
  "descubramos que la membresía VIP incluye beneficios que ni sabíamos que existían",
  "alguien tenga que aflojarse el cinturón después del segundo almuerzo del día",
  "la familia necesite una reposera extra solo para la digestión colectiva post-buffet",
  "el buffet del Palladium tenga flashbacks de nuestra visita durante los próximos 5 años",
  "alguien haga un brindis con un coctel tropical diferente cada noche de los 9 días",
  "la familia pruebe absolutamente todos los restaurantes del hotel en los primeros 3 días",
  "alguien descubra que hay pizza a las 4 AM, lo grite al pasillo y despierte a medio piso",
  "la familia convierta cada comida del día en una reunión familiar extendida de 2 horas",
  "el Palladium contrate personal de refuerzo para el buffet cuando vea nuestra reserva de 19",
  "alguien pregunte si existe un límite de visitas al buffet por día y le digan que no",
  "descubramos que la mejor propina en el all-inclusive es la sonrisa genuina al barman",
  "la familia le dé una masterclass práctica a otros huéspedes sobre cómo exprimir el all-inclusive",

  // ═══════════════════════════════════════════════════════════════
  // PATRIARCADO / HOMBRES (~15)
  // ═══════════════════════════════════════════════════════════════
  "los hombres finjan que ayudan a empacar las valijas mientras miran el partido en el celular",
  "los hombres digan 'yo llevo las valijas' como si fuera una proeza del patriarcado argentino",
  "los hombres se ofrezcan a 'cuidar las reposeras' mientras las mujeres llevan a los nenes a la pileta",
  "los hombres descubran que en el all-inclusive también hay que servirse solos el plato",
  "los hombres debatan 40 minutos a qué restaurante ir y terminen todos en el buffet de siempre",
  "los hombres digan 'yo me encargo de la logística' y terminen pidiendo indicaciones a las mujeres",
  "Bruno, Nani y Sebastian digan 'nosotros armamos el plan' y Pamela, Vanesa y Silvia lo rehagan entero",
  "los hombres se adjudiquen haber elegido el resort después de que las mujeres lo investigaron durante semanas",
  "los hombres se quejen de la crema solar y las mujeres los embadurnen a la fuerza como a nenes",
  "Daniel, Omar y Alejandro se sienten en la reposera a 'pensar' mientras los demás organizan todo",
  "los hombres lleven una valija cada uno y las mujeres lleven la logística completa de 19 personas",
  "los hombres propongan 'actividad de hombres' que consiste únicamente en ir a la barra",
  "los hombres digan que ellos coordinaron el viaje sin saber ni la dirección del resort",
  "Sebastian diga 'yo organicé todo el viaje' cuando su mamá le armó la valija",
  "los hombres se atribuyan el éxito del viaje en la cena de despedida y las mujeres se miren entre ellas",

  // ═══════════════════════════════════════════════════════════════
  // VUELOS / AEROPUERTO (~15)
  // ═══════════════════════════════════════════════════════════════
  "Silvia cree un grupo de WhatsApp con las reglas oficiales del viaje y mande 47 audios",
  "alguien se olvide el pasaporte en casa y haga entrar en pánico a toda la familia en Ezeiza",
  "Omar se queje del proceso de check-in de Arajet como si fuera una odisea griega",
  "alguien lleve más equipaje de mano que equipaje facturado y lo paren en el gate",
  "los nenes pregunten '¿ya llegamos?' antes de que el avión de Arajet despegue",
  "Stella desinfecte el asiento de Arajet con toallitas antibacteriales como en una operación quirúrgica",
  "alguien descubra en el aeropuerto que Arajet tiene asignación libre de asientos",
  "19 personas intenten coordinarse para sentarse cerca en el avión de Arajet sin éxito",
  "Omar se agarre del apoyabrazos en cada mínima turbulencia y le rece a tres santos distintos",
  "alguien se lleve medio buffet del aeropuerto de Ezeiza 'para el viaje de 5 horas'",
  "la familia ocupe una fila completa del gate de embarque en Ezeiza",
  "alguien intente despachar una botella de Sidra 1888 como equipaje frágil con total seriedad",
  "19 argentinos hagamos la fila más ruidosa y divertida del aeropuerto de Ezeiza",
  "Omar googlee las últimas reviews de Arajet en el gate de embarque como última verificación",
  "alguien se emocione al ver el mar turquesa desde la ventanilla y bloquee la vista 2 horas",

  // ═══════════════════════════════════════════════════════════════
  // FAMILIAS COMBINADAS / GENERAL (~30)
  // ═══════════════════════════════════════════════════════════════
  "19 personas intenten ponerse de acuerdo para una sola foto grupal decente",
  "la familia necesite juntar 3 mesas para poder cenar todos juntos en el restaurante",
  "el resort aprenda por las malas que los argentinos viajamos siempre en manada",
  "alguien proponga dividir la cuenta de algo y todos le recuerden que es all-inclusive",
  "la familia haga más ruido que la animación oficial del hotel",
  "19 personas intenten elegir una excursión grupal y terminen todos en la pileta como siempre",
  "la familia ocupe un sector completo de la playa como si fuera territorio argentino",
  "alguien se pierda en el resort y 18 personas salgan a buscarlo como operativo policial",
  "la familia haga una videollamada a Marcela desde la playa solo para mostrarle lo que se pierde",
  "19 argentinos descubramos que en el Caribe no hay mate pero hay felicidad all-inclusive",
  "la familia se acuerde de este viaje como el mejor de toda la vida",
  "alguien se emocione viendo a 4 generaciones de la familia juntas en una playa del Caribe",
  "la familia entera se queme el primer día porque nadie le hizo caso a Stella con el protector",
  "19 personas logren coordinarse para una excursión sin que sea un completo desastre logístico",
  "la familia convierta el restaurante del hotel en una mesa de Navidad argentina",
  "alguien diga '¿y si el año que viene repetimos?' al segundo día del viaje",
  "la foto grupal en la playa de Punta Cana se convierta en la foto familiar más épica de la historia",
  "la familia entera se duerma en las reposeras después del almuerzo como Daniel en la siesta",
  "alguien se pierda el show nocturno del hotel porque se quedó dormido de la comilona",
  "19 personas descubramos oficialmente que somos la familia más ruidosa del Palladium",
  "la familia grabe un video para el grupo de WhatsApp que dure más de 47 minutos",
  "alguien proponga hacer una actividad deportiva y todos terminen en la barra VIP",
  "la familia necesite una logística de mudanza para ir del hotel a la playa con los 19",
  "19 argentinos exportemos el concepto del asado como patrimonio cultural al Palladium",
  "alguien diga 'la próxima traemos a toda la familia' y todos miremos la silla vacía de Marcela",
  "la familia pose para más fotos grupales que en un casamiento completo",
  "alguien se duerma en el lobby esperando a que los 18 restantes se terminen de preparar",
  "la familia descubra que 9 noches all-inclusive no son suficientes para hacer todo lo planeado",
  "alguien llore genuinamente en el aeropuerto de vuelta porque no quiere volver a la realidad",
  "19 personas en 4 generaciones demuestren que la felicidad es un all-inclusive familiar en Punta Cana",
];
